// Time based badassery: count the days from IWD to IWD to make a reference to the badasses in the badass array.

var oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds
var firstDate = new Date(2017, 02, 09);
var secondDate = new Date(2018, 02, 08);

var diffDays = Math.round((firstDate.getTime() - secondDate.getTime()) / (oneDay)) + 365;

var randomNumber = -1;

//==============================================================
//BADASSES
//==============================================================

var badass = new Array();
// data format for badasses: name (0), nickname or sub-head (1), link (2), short bio (3), image (4)
badass.push(["Maude Abbott","The Heart of the Matter","I'll give you three guesses why super-genius Maude Abbot was rejected by McGill University in 1886. You're only going to need one. As the first in a series of epic eye-rolls followed by delicious victories, Maude later became the first woman to receive a B.A. from McGill under a full scholarship, and became a world authority on life-saving heart surgery. But, you know, probably women shouldn't go to university.","img/default","https://en.wikipedia.org/wiki/Maude_Abbott","dark"]);
badass.push(["Mary Electa Adams","Badass Chief Preceptress ","Mary Adams held the radical belief that women – wait for it – have brains. Mary traveled all over talking this crazy talk before becoming \"Chief Preceptress,\" (read: \"Boss Lady\") of a school in Sackville, New Brunswick and completely reforming their crap female education programs. Mary felt like, in addition to learning to read the Bible, women could benefit from studying, say, science, mathematics, moral philosophy and Latin. YEP!","img/default","https://en.wikipedia.org/wiki/Mary_Adams_(educator)",""]);
badass.push(["Emma Albani","Qu&eacute;b&eacute;cois Idol","When Emma Albani discovered professional singing was a distasteful career for a woman, she said: \"Okay, I'll just be a nun.\" Pffffft. JK! As a teenager with pipes that'd make Simon Cowell weep, Emma moved to New York and worked odd jobs to afford continuing her musical education. At her debut performance, fans threw LIVE DOVES at her FACE (which, turns out, is a good thing).","img/default","https://en.wikipedia.org/wiki/Emma_Albani",""]);
badass.push(["Maud Allan","Lewd Lesbian in London","For Maud Allan, \"bold,\" doesn't even come close. Musician, dancer, choreographer and unapologetic social-norms-challenger, in 1918 Maud sued the small-minded MP who accused her of sexual perversion (same guy who thought homosexuals were secretly behind WWI... yeah) in a sensational trial that drew much-needed attention to freedom of expression and the arts. Maud lost the trial, but you don't see us celebrating Mr. Jerkface MP a century later.","img/default","https://en.wikipedia.org/wiki/Maud_Allan",""]);
badass.push(["Anna Mae Aquash","Advocacy for Anna","As people with functioning brains already know, fighting to correct blatant prejudice and inequality is a – wait for it – GOOD thing, and should be encouraged. Influential Mi'kmaq activist Anna Mae Aquash never got the chance to live her potential. With two small daughters at home, Anna was murdered on account of her strong voice. Anna knew that change was possible. Let's not let her down.","img/default","https://en.wikipedia.org/wiki/Anna_Mae_Aquash",""]);
badass.push(["Edith Jessie Archibald","","","img/default","https://en.wikipedia.org/wiki/Edith_Archibald",""]);
badass.push(["Elizabeth Arden","Maybe She's Born with It","Florence Nightingale Graham – wait, who? – landed a job as a \"treatment girl\" before debuting a new name and salon in 1910. Elizabeth did today's cosmetic stars a solid by teaching women how to apply makeup and making it socially respectable to wear day-to-day. Lady boss hired chemists to produce her youth-promising creams, and took that shiz to the bank. Florence, Lizzy – don't matter. Sister died a millionaire.","img/default","https://en.wikipedia.org/wiki/Elizabeth_Arden",""]);
badass.push(["Helen Armstrong","Wild Woman of the West","Helen Armstrong believed that women should be paid the same as men for the work that they do. Oh, and that they shouldn't need to ask for that, because DUH. Helen's campaigning skills were top shelf, but girlfriend never gets enough credit for the mountains she moved. Helen, thanks for picketing at 5 AM when you had small children at home so your sisters could feed their own. #respect","img/default","https://en.wikipedia.org/wiki/Helen_Jury_%E2%80%9CMa%E2%80%9D_Armstrong",""]);
badass.push(["Kenojuak Ashevak","","","img/default","https://en.wikipedia.org/wiki/Kenojuak_Ashevak",""]);
badass.push(["Elizabeth Bagshaw","She Did It Her Way","Elizabeth Bagshaw persevered through threatening (and idiotic) public scorn to provide desperately needed medical care in Canada's first illegal birth control clinic. That's so bold and brave I can't even make a joke about it. Elizabeth lived her whole life progressively, not giving half a crap if people disapproved, and died a centurion member of the Order of Canada.","img/default","https://en.wikipedia.org/wiki/Elizabeth_Bagshaw",""]);
badass.push(["Mary \"Bonnie\" Baker","There’s No Crying","The All-American Professional Baseball League. Ever heard of it? How about the woman the press called \“Pretty Bonnie Baker,\" but who the scorecard called: Pro-AF Boss Lady. (Perhaps their wording was different, it’s whatever.) After 930 games of butt-kicking, and serving as the league’s first and only female player-manager, “Pretty Bonnie” casually transitioned into the role of first female sports broadcaster in Canada.","img/default","https://en.wikipedia.org/wiki/Bonnie_Baker",""]);
badass.push(["Frances Barkley","Superstition Overboard","A woman aboard? Blasphemy! Though, this was back in the day when scurvy was God's punishment for laziness, and bonnets were scandalously sexy. So. What's a woman desperate for the deep blue to do? Disguise herself – as a man! Or she could pull a Frances Barkley: marry a sea-captain, and tag along to become the first woman ever to see Canada's west coast, and circumnavigate the world - undisguised.","img/default","https://en.wikipedia.org/wiki/Frances_Barkley",""]);
badass.push(["Robertine Barry","Mightier than the Sword","Robertine Barry thought marriage was nice and all, but wasn't \"the goal to which must be devoted a lifetime of noble efforts.\" Professional journalism on the other hand: heck yeah! Through scorn and reprimand, Barry became the first woman hired full time by a Quebec paper. Years later, Barry's own journal, Le Journal de Françoise, granted other sister writers their first big breaks. ","img/default","https://en.wikipedia.org/wiki/Robertine_Barry",""]);
badass.push(["Margaret Benedictsson","","","img/default","http://www.thecanadianencyclopedia.ca/en/article/margret-benedictsson/",""]);
badass.push(["Myra Bennett","","","img/default","https://en.wikipedia.org/wiki/Myra_Bennett",""]);
badass.push(["Mary Bibb","","","img/default","https://en.wikipedia.org/wiki/Mary_E._Bibb",""]);
badass.push(["Lucie Blackburn","","","img/default","http://www.pc.gc.ca/APPS/CP-NR/release_e.asp?bgid=503&andor1=bg",""]);
badass.push(["Fern Blodgett","A Decorated Marine","Little Fern Blodgett grew up in Ontario watching ships on the great lakes and was like, \"Imma sail one of those one day!\" And her parents were all: \"But Fern, you're a girl.\" And Fern looked at them very seriously and replied, \"I SAID, I'm going to SAIL ONE OF THEM FANCY SHIPS.\" And wouldn'tcha knowit? Baby Fern became the first Canadian woman to serve in the Merchant Marines.","img/default","http://www.thewhig.com/2015/03/03/international-womens-day-fern-blodgett-sunde-a-warships-wireless-officer",""]);
badass.push(["Esther Brandeau","The First Jewish Girl in Canada","Esther Brandeau lied about basically everything that matters just to see the magical place they call: Canada. Makes ya feel special, eh? Disguised as a boy and denying her religion, Esther hung out on the St. Michel en route to New France before both her gender and Judaism were discovered (oops). When faced with Catholic conversion (\"C'mon, Esther. All your friends are doing it.\") Esther decided \"…nah,\" and was deported. ","img/default","https://en.wikipedia.org/wiki/Esther_Brandeau",""]);
badass.push(["Roberta Bondar","When I Grow Up, I Want to Be a Roberta Bondar.","Roberta Bondar has 22 honorary degrees. I could stop right here, but just for kicks let's keep going. First Canadian woman in space, (not bad, I guess), received the Order of Canada (yep, mmhmm), and was inducted into the Canadian Medical Hall of Fame because she's also a freakin neurologist. You know, a brain doctor. IT'S WHATEVER, THO, ROBERTA; leave some awesome for the rest of us mmkay?","img/default","https://en.wikipedia.org/wiki/Roberta_Bondar",""]);
badass.push(["Marguerite Bourgeoys","That Lady was a Saint. No, Seriously.","Marguerite Bourgeoys saved orphans and educated the poor regardless of their gender or heritage. Sound saint-like? The Pope thought so, too. St. Marguerite also really, reeeeeally wanted to teach outside the convent, taking three separate trips to France in the 1600s to convince the local bishops. After getting her wish, Marguerite turned her saint-ness up to 11, establishing schools and saving people from death. (NBD.)","img/default","https://en.wikipedia.org/wiki/Marguerite_Bourgeoys",""]);
badass.push(["Molly Brant","","","img/default","https://en.wikipedia.org/wiki/Molly_Brant",""]);
badass.push(["Harriet Brooks","","","img/default","https://en.wikipedia.org/wiki/Harriet_Brooks",""]);
badass.push(["Rosemary Brown","Brown is Beautiful","Rosemary Brown received 15 honorary doctorates from Canadian universities. *Drops the mic.* FIFFTEEN. Why? Let's explore: First black female member of a provincial legislature. First woman to run for leadership of a federal political party. Founding member of the Vancouver Status of Women Council. CEO of advocacy group MATCH International Women's Fund. Chief commissioner of the Ontario Human Rights Commission. Rosemary! Dang, girl. You killin' it. ","img/default","https://en.wikipedia.org/wiki/Rosemary_Brown_(politician)",""]);
badass.push(["Emily Carr","Becoming a National Icon","Some people (you) are described as Canadian. Other people (not you) are described as inspiring Canadian icons. But don't worry – there's totally hope! All you've gotta do is: represent the national imagination through incredible innovative art, win a couple writing awards, succeed against basically all odds and have a bunch of institutions named for your bravery. So like, probably get going on that.","img/emily-carr","https://en.wikipedia.org/wiki/Emily_Carr",""]);
badass.push(["Th&eacute;r&egrave;se Casgrain","A Force to be Reckoned with","When the Quebec government told T&eacute;r&egrave;se Casgrain she wasn't allowed to vote, she was like, \"Aw, sweetie. It's so cute that you think that!\" Then she hosted a feminist radio show, became the first female leader of a Canadian political party, helped found the League for Human Rights and became a freaking SENATOR. Oh, and cast a few delicate lady votes with her delicate lady fingers.","img/default","https://en.wikipedia.org/wiki/Th%C3%A9r%C3%A8se_Casgrain",""]);
badass.push(["Ethel Catherwood","The \"Prettiest Girl\" at the Games","Ethel Catherwood was a kickass, gold-medal winning Saskatoonian who didn't give two hoots about other people's dumb opinions. After killin' it at the 1928 Olympics, Ethel got secretly married and divorced in Reno, while the press were all \"BUT ETHEL!\" and Ethel was like, \"You know what, I don't do interviews.\" This athletic goddess brought home what is still Canada's only track-and-field female gold. Ethel. Saskatchewan Sports Hall-of-Famer.","img/ethel-catherwood","https://en.wikipedia.org/wiki/Ethel_Catherwood",""]);
badass.push(["Victoria Cheung","","","img/default","http://chinatown.library.uvic.ca/node/860",""]);
badass.push(["Laure Conan","Something to Write About Home","Marie-Louise-F&eacute;licit&eacute; Angers, or, \"Laure Conan\" to her readers, was a French Canadian author born in 1845. That's the same 1845 that had women tied up in corsets, cooking and baby-making. Mhmm. Girlfriend remained unmarried, and wrote ELEVEN novels. Laure's style explored the minds of her characters within contemporary Quebec family structure, while the real life lady told traditional Quebec family structure where they could shove it. #allthesingleladies ","img/default","https://en.wikipedia.org/wiki/Laure_Conan",""]);
badass.push(["Flora MacDonald Denison","","","img/default","http://www.thecanadianencyclopedia.ca/en/article/flora-macdonald-denison/",""]);
badass.push(["Carrie Derick","Genius Geneti-sister","What did years of tireless no-crap taking and relentless research in genetics get Carrie Derick? 3 points for guessing \"the honour of becoming Canada's first female university professor.\" Minus 2 points for forgetting that she was awarded a third the salary of her male counterparts. And this was after she did everything to earn her PhD (except have a penis).","img/carrie-derick","https://en.wikipedia.org/wiki/Carrie_Derick",""]);
badass.push(["Viola Desmond","Viola Victorious","When she was told to leave the whites-only area of a Nova Scotia theatre in 1946, Viola Desmond told those racist jerks to shove it. (Basically she said that.) But the wildly unjust tax violation charge (for ONE CENT) brought against her when she refused to leave made her case famous, and helped launch the civil rights movement in Canada. For more Viola, keep your eyes on the $10 bill…","img/default","https://en.wikipedia.org/wiki/Viola_Desmond",""]);
badass.push(["Pauline Donalda","Nice Work if You Can Get It","Montreal born Pauline Donalda was 22 years old when her operatic debut in Nice, France dropped everyone's jaws. After performing all over Europe and America, she retired at 40 to devote her life to fostering new talent. With young singers on the rise and two husbands left in the dust, Pauline lived up to her motto: You must work, work, work! ","img/default","https://en.wikipedia.org/wiki/Pauline_Donalda",""]);
badass.push(["On&eacute;sime Dorval","Woodwork it, grrrl.","A literal trailblazer (no seriously) On&eacute;sime Dorval walked ahead of an oxcart caravan across the Prairies for two months in the 1880s to arrive in the bustling metropolis (read: tiny armpit settlement) of Duck Lake, Saskachewan. Ignoring the fires, mosquitoes, dust, and bad food, On&eacute;sime became Saskatchewan's first teacher and a pioneer of bilingual education. Oh and she could paint and woodwork like a boss, because why not.","img/default","https://en.wikipedia.org/wiki/On%C3%A9sime_Dorval",""]);
badass.push(["Allie Vibert Douglas","Viberts are from Venus","Want both an asteroid and a crater on Venus named after you? Step 1: Get tossed out of the stupid boys-only science club in high school. Step 2: Become the first woman in North America to earn a PhD in astrophysics. Step 3: Savour a really awkward high-school-reunion conversation with your former (male) science teacher.","img/default","https://en.wikipedia.org/wiki/Vibert_Douglas",""]);
badass.push(["Mary Two-Axe Earley","Sexism Got the Chop","Some people, who may or may not be Mary Two-Axe Earley, receive National Achievement awards for their commitment to women's rights, specifically correcting gender discrimination within the Indian Act. Some people are also powerful Clan Mothers who devote their whole lives to organizing and campaigning for justice. They also hold a doctorate from York. Actually, yeah, that's all just Mary Two-Axe Earley. She's basically a one-of-a-kind.","img/default","https://en.wikipedia.org/wiki/Mary_Two-Axe_Earley",""]);
badass.push(["Sarah Emma Edmonds","Cash me Outside …Fighting in the Civil War.","Not particularly interested in an arranged marriage, Sarah Emma Edmonds left her native New Brunswick for the United States at just 15. Told she couldn’t serve her adopted country, Sarah \"I-Do-What-I-Want\" Edmonds rolled her eyes, and simply disguised herself as a man. Her book, Nurse and Spy in the Union Army, sold 175,000 copies.","img/default","https://en.wikipedia.org/wiki/Sarah_Emma_Edmonds",""]);
badass.push(["Henrietta Muir Edwards","Stop the Presses","With no Jezebel or Lenny Letter — not even a tattered back issue of Ms. magazine — 19th-century feminists desperately needed something to read that didn't totally suck. So, Henrietta Muir Edwards and her sister trained an all-female staff to put out Woman's Work in Canada, the first Canadian 'zine for working women. Move over, Riot Grrrl. We got this.","img/default","https://en.wikipedia.org/wiki/Henrietta_Edwards",""]);
badass.push(["Leone Norwood Farrell","","","img/default","http://www.healthheritageresearch.com/Farrell/Farrell-TS20050417.html",""]);
badass.push(["Faith Fenton","Have Faith. ","Born in 1857, Alice Freiman grew up to be a school teacher. However, teaching arithmetic to snot-nosed monsters was rather unsatisfying, and the super sexist age didn't offer that many other options. So, naturally, Alice took the pseudonym of Faith Fenton and became a investigative journalist. \"Faith\" tackled contentious subjects like sexual discrimination, harassment, child abuse, and unfair pay, while \"Alice\" taught school. ","img/default","https://en.wikipedia.org/wiki/Faith_Fenton",""]);
badass.push(["Joan Bamford Fletcher","Welcome to the Super Not Safe I Don't Want to Be Here This Isn't Fun Anymore  Jungle. ","So. You're in Sumatra with 2,000 Dutch civilian prisoners at the end of WWII. What do you do!? Rally them up and walk to safety through a dangerous jungle full of Indonesian rebels, duh. Then the Queen gives you a fancy medal and you get all sorts of other accolades for doing this awesome thing. Also your name is Joan Bamford Fletcher (sorry, should have told you that part sooner...).","img/default","http://esask.uregina.ca/entry/bamford_fletcher_joan_1918-79.html",""]);
badass.push(["Lillian Bilsky Freiman","Make Poppies, Not War","Next time you accidentally poke yourself with a Remembrance Day poppy, you can thank philanthropist Lillian Freiman. No, she didn't begin the poppy campaign in Canada to annoy you (seriously, everything isn't about you...) she did it to help World War I veterans. Oh, and she saved a bunch of Jewish war orphans too. So get over your #firstworldproblems and bow down to the Poppy Lady.","img/default","https://en.wikipedia.org/wiki/Lillian_Bilsky_Freiman",""]);
badass.push(["Rose Fortune","","","img/default","https://en.wikipedia.org/wiki/Rose_Fortune",""]);
badass.push(["Dr. Ursula Franklin","Do All the Things","It might be easier to talk about what Ursula Franklin didn’t do, instead of what she did. Can we do that? No? C'mon. Dr. Franklin was a world-renowned physicist, writer, peace activist, feminist, and a tireless advocate for human rights. She survived the Nazi atrocities, immigrated to Canada, and then she did a lot more stuff that'll make you feel like, \"What have I done today?\". Amazing.","img/default","https://en.wikipedia.org/wiki/Ursula_Franklin",""]);
badass.push(["Marie G&eacute;rin-Lajoie","Sisters Doin' It for Themselves","Marie G&eacute;rin-Lajoie has some buildings and streets named after her. Probably because she lived a really boring life and never did anything important. Or, possibly, it's because she was an author, educator, social activist and suffragist BOSS. Marie was a self-taught legal expert (what, like it's hard?) and was fighting for the vote in Quebec before you were even born. How about a nice little thank you for Marie, huh?","img/default","https://en.wikipedia.org/wiki/Marie_Lacoste_G%C3%A9rin-Lajoie",""]);
badass.push(["Hilwie Hamdon","The First Mosque in Alberta","Born in Lebanon in 1917, Hilwie Hamdon emigrated to northern Alberta as a teenage bride. No sweat! After settling in Edmonton, Hilwie couldn't help but notice that the super-white, colonial town offered no central hub for the Muslim community. Her friends were like: \"We should build a hall\" and Hil' was all, \"How 'bout we build a mosque?\" So she DID. It was Canada's first mosque.","img/default","https://edwomencan.wordpress.com/2008/12/18/women-behind-al-rashid-mosque/",""]);
badass.push(["Hattie Rhue-Hatchet","She's Got the Beat","Hattie was born during the Civil War, the child of escaped slaves. Her family came to the Elgin Settlement (a great story in its own right, seriously, look it up) and she took to music from a young age. Against literally all odds, Hattie was a revered music teacher, songwriter, and composer in what is now North Buxton, Ontario.","img/default","http://www.virtualmuseum.ca/edu/ViewLoitDa.do;jsessionid=3A18487C7BFDB29E6A26C89EC94DFEC0?method=preview&lang=EN&id=18664",""]);
badass.push(["Ann Harvey","The Grace Darling of Newfoundland","When she was 17 years old Ann Harvey helped save 163 people from a wrecked ship headed for Quebec City. One hundred. And sixty. Three. People. What you were doing when you were 17?! Oh, and one more tidbit about good ol' Ann: 10 years later, she saved another 25 people from a different shipwreck at the same spot. (Maybe stop sailing there? I don't know?) ","img/default","https://en.wikipedia.org/wiki/Ann_Harvey",""]);
badass.push(["Anne H&eacute;bert","Triple Threat","Throughout her long and varied career as a poet, playwright and novelist, Anne H&eacute;bert earned a list of accolades that basically makes her the Beyonc&eacute; of French-Canadian literature. Plus, this single lady won the Governor General's Award three times. And she was appointed a Companion of the Order of Canada. Who run the world, indeed.","img/anne-hebert","https://en.wikipedia.org/wiki/Anne_H%C3%A9bert",""]);
badass.push(["Esther Hill","A Redesigned Glass Ceiling ","What would city skylines look like if trailblazing women architects like Esther Hill hadn't been shoved in the margins? (Hint: maybe there would be fewer buildings out there that look like giant penises.) Our girl Esther didn't get enough chances to build her dreams — you suck, misogyny — but she still broke barriers in the male-dominated, hugely overcompensating world of architecture. ","img/default","https://en.wikipedia.org/wiki/Esther_Hill",""]);
badass.push(["Lotta Hitschmanova","Ride into the Conflict Zone","Prague born Lotta Hitschmanova achieved her PhD in journalism and French studies in order to freelance-write the heck out of some anti-Nazi sentiments. When Germany was all \"Hey, that's not cool,\" Dr. Lotta fled to Belgium, then France, and finally Canada. Less than 100 lbs. and with $60 in her pocket, Lotta quickly excelled, devoting the rest of her life to offering relief to war torn Europe. ","img/default","https://en.wikipedia.org/wiki/Lotta_Hitschmanova",""]);
badass.push(["Helen Sawyer Hogg","Far out, man. ","\"Reach for the stars\" is just a saying, Helen. No, Helen, It's FIGURATIVE, HELEN. Well, whatever. Helen Sawyer-Hogg wasn't great with metaphors, so she pioneered research into globular clusters and variable stars. Then, she became president of several astronomical organizations when most universities were like \"Oh, yeah no. No you're a girl, so. Nope.\" Asteroid 2917 Sawyer Hogg is named after... well, you figure it out. ","img/default","https://en.wikipedia.org/wiki/Helen_Sawyer_Hogg",""]);
badass.push(["Adelaide Hunter Hoodless","Knowledge is Power","After the death of her infant son in 1889 from meningitis, possibly brought on by poor hygiene practices, Adelaide Hoodless had had enough. In a world where no one tells you anything when you have lady parts, Adelaide thought, \"This is ridiculous,\" and began what would become the Women's Institute, where women gather to educate each other about important issues relating to their lives. ","img/default","https://en.wikipedia.org/wiki/Adelaide_Hoodless",""]);
badass.push(["E. Pauline Johnson","The Best of Two Worlds","Too exotic to her white family, and too white for her aboriginal cousins, \"Tekahionwake\" (literally, \"double-life\") E. Pauline Johnson experienced some pretty nasty discrimination growing up mixed race. But this artist and writer wasn't about to throw in the proverbial, Victorian towel. Pauline celebrated her mixed heritage through poems and performance, becoming an anthologized Canadian icon.","img/default","https://en.wikipedia.org/wiki/E._Pauline_Johnson",""]);
badass.push(["Leonora King","Double Dragon Doctor","Rejected by Canadian medical schools for having lady parts, Leonora King took her lady brain to the U.S. and became a doctor anyway. A missionary doctor in China for 47 years, she was granted the Order of the Double Dragon and became a mandarin of the Chinese court. The honour brought her fame AND an ermine coat. #fashioninspo","img/default","https://en.wikipedia.org/wiki/Leonora_King",""]);
badass.push(["Tsukiye Muriel Kitagawa","Everything to Write Home About","Tsukiye Muriel Kitagawa was born in Vancouver (a second generation Japanese Canadian) in 1912, and then unceremoniously forced into internment in 1942 because of her Japanese heritage. Tsukeye thought this was a pretty condemnable (YEP) and thought it deserved to be written about (YEP) so that's what she did. Her excellent essays highlight injustices to which Canada must be held accountable.","img/default","https://remarkablewomen2014.wordpress.com/2013/09/26/muriel/",""]);
badass.push(["Elsie Knott","","","img/default","https://en.wikipedia.org/wiki/Elsie_Knott",""]);
badass.push(["Molly Kool","More like: Molly so freakin' Kool, amiright?","Molly, Molly, Molly. Don't you know women aren't supposed to be sea captains? Wait, you don't? Oh, ok then. After lady-boss earned her official captain's stripes in 1939 Nova Scotia, a line in the Canadian Shipping Act had to be changed to include the word \"she.\" Heck yeah, Molly. And way to go on the whole being a ship-master thing, too.","img/default","https://en.wikipedia.org/wiki/Molly_Kool",""]);
badass.push(["Marguerite Vincent Lawinonki&eacute;","These Shoes are Made for Culture-Rescuing ","Marguerite Vincent Lawinoki&eacute; took moose-hair and porcupine quills and turned them into on fleek works of orthopedic ART. (Shoes. She made super cool shoes.) Her creations literally helped save her village, and have preserved Huron-Wendat culture for generations. Marguerite's community decided to make this whole shoe business thing their official jam, and now over 60 families produce over 30000 moccasins every year. All. By. Hand. ","img/default","https://en.wikipedia.org/wiki/Marguerite_Vincent_Lawinonki%C3%A9",""]);
badass.push(["Florence Lawrence","Eat Your Heart Out, Hollywood","Considered the \"The First Movie Star,\" Florence Lawrence appeared in over 300 films. 300. That's… that's a lot of freakin' films. Oh, and also owned a successful store. And was an automotive inventor. And had her own line of cosmetics. Probably she had lots of time for these things because she wasn't in that many fil… oh, wait.","img/default","https://en.wikipedia.org/wiki/Florence_Lawrence",""]);
badass.push(["Irma LeVasseur","Dr. LeVasseur. You Heard Right. ","In 1900, when Quebec told Irma LeVasseur that women can't be doctors, Irma said: \"That's nice. I'm going to become a doctor tho, so…\" After practising medicine in New York City, her relentless determination resulted in the passing of a private bill in the Quebec Assembly allowing her to practice at home. The first female Quebec physician, she also helped establish several hospitals. We think that's, you know, pretty cool. ","img/default","https://en.wikipedia.org/wiki/Irma_LeVasseur",""]);
badass.push(["Jean B. Lumb","Yep, That's \"B\" for \"Badass\"","When Jean B. Lumb noticed that Chinese families were suffering separation due to laughably racist immigration laws, she sat down on the chesterfield and said, \"Oh well, that's life.\" JK!!! Jean got that baloney straightened out, and went on to save a couple Chinatowns in the process. Oh, and she owned a grocery store and raised six kids at the same time NBD. ","img/default","https://en.wikipedia.org/wiki/Jean_B._Lumb",""]);
badass.push(["Elsie MacGill","Queen of Hurricanes","The first female airplane designer and the world's first woman to earn an aeronautical engineering degree, Elsie MacGill wore the pants. (Which was super scandalous at the time, oh my.) Elsie contracted polio and was told she'd never walk again, but girlfriend didn't have time for that noise. She engineered herself some canes so she could continue her day-to-day of being an absolute boss. ","img/elsie-macgill","https://en.wikipedia.org/wiki/Elsie_MacGill",""]);
badass.push(["Helen Gregory MacGill","In Tune and Out of Sync","You know when you're up to your eyeballs in being the first female judge in British Columbia and the only one in Canada, and also writing as a journalist on the side for Cosmopolitan, and also, you know, fighting for women's rights every day, you think: \"I should be the first woman in the entire British Empire to earn a music degree?\" No? Just Helen Gregory MacGill? K.","img/default","https://en.wikipedia.org/wiki/Helen_Gregory_MacGill",""]);
badass.push(["Viola R. MacMillan","","","img/default","https://en.wikipedia.org/wiki/Viola_R._MacMillan",""]);
badass.push(["Helen MacMurchy","Public Health Champion","Do you think that Helen MacMurchy gave a shi... nbone that in the 1890s, women didn't typically work in medicine? Hmm? Do ya? After gaining valuable first-hand experience with childbirth, Helen wrote a book for mothers (wait, women can read?) that mixed medical research with common language, which was all sorts of practical. Way to save them babies, Helen.","img/default","https://en.wikipedia.org/wiki/Helen_MacMurchy",""]);
badass.push(["Agnes Campbell Macphail","Lady-like Legislating","Agnes Campbell Macphail knew a thing or two about… well, kind of everything. The first woman to be elected to parliament, she worked for two separate Canadian parties and was a strong voice for rural issues and penal reform. Agnes said it best: \"Most women think politics aren't lady-like. Well, I'm no lady. I'm a human being.\" #AGNES. ","img/default","https://en.wikipedia.org/wiki/Agnes_Macphail",""]);
badass.push(["Clara Brett Martin","Clara Martin,  Juris Doctor","Clara Brett Martin was a smart little girl who (got her B.A. in mathematics at 16) did lots of nice things (petitioned the Law Society of Upper Canada to let her in despite her gender) had nice hobbies (paved the way for female lawyers in Canada) and read lots of nice books (understood the importance of education to the future for Canadian women). You know, nice stuff like that.","img/clara-brett-martin","https://en.wikipedia.org/wiki/Clara_Brett_Martin",""]);
badass.push(["Nellie McClung","Let Them Howl","One time, someone told Nellie McClung she couldn't vote. \"Um, yeah I don't like that. We should probably change that,\" she said. So …she did. After a whole life dedicated to women's rights, including notable victories like getting women \"person\" status under the law, Nellie says it best: \"Never explain, never retract, never apologize. Just get the thing done and let them howl.\" Heck. Yes. Nellie. #howlyourheartout","img/default","https://en.wikipedia.org/wiki/Nellie_McClung",""]);
badass.push(["Frances Gertrude McGill","Sherlock Holmes of Saskachewan","To make 1 Frances Gertrude McGill: Gather all characters from CSI, and blend. Remove all clich&eacute; catch lines and sunglasses. Remove modern conveniences. Add incredible perseverance to master fields previously reserved for men. Add medals for highest student average. Add bacteriologist experience. Add pathologist experience. Finally, add this personally coined motto: \"Think like a man, act like a lady and work like a dog.\" Mix well, serve immediately.","img/default","https://en.wikipedia.org/wiki/Frances_Gertrude_McGill",""]);
badass.push(["Louise McKinney","Feminist Elect","There are reasons the Famous Five are, well, famous. Louise McKinney persevered through moronic sexism at best, physical threats at worst, to become the first woman sworn into the Legislative Assembly of Alberta (hence also the first woman elected to a legislature in Canada and the British Empire). Tough as nails and resiliant-af, McKinney favoured \"radical\" ideas like female education, and women's property rights. ","img/default","https://en.wikipedia.org/wiki/Louise_McKinney",""]);
badass.push(["Maud Menten","\"Petite Dynamo\" aka Dr. Boss","When Canada told physician-scientist Maud Menten she wasn't allowed to do research here because of her bad luck in the genetic lottery, she was like \"Whatever dudes. I'll take my genius elsewhere.\" Turns out Germany was very happy to have her, awarding her a PhD in 1916. Besides enormously advancing her field, Maud's personal interests were freaking awesome: mountain climbing, painting, language-learning, astronomy, girl. Way to go.","img/default","https://en.wikipedia.org/wiki/Maud_Menten",""]);
badass.push(["Mikak","I'm not exotic YOU ARE.","Mikak was an Inuk woman from 1740 Labrador who didn't give a canoe that most of her people were afraid of the Europeans. Smart, industrious and brave-af, Mikak was the first Inuit woman to travel to Europe and return back to Canada, and share stories that went something like: \"They're all as white and fragile as snow, you guys. They're basically screwed.\"","img/default","https://en.wikipedia.org/wiki/Mikak",""]);
badass.push(["Dorothea Mitchell","Lady Lumberjack","Dorothea Mitchell did the following things on her own, while unmarried: Gained a homestead in Ontario. (Gasp!) Purchased a sawmill and hired workers. (What!?) Took a filthy cheat to court, and won. (For real?) Excelled at photography and writing. (Ok stopit.) Made several films. (Well this is just OUTRAGEOUS.) Oh, and kicked butt at absolutely ALL of it. So, what have you been up to lately?","img/default","https://en.wikipedia.org/wiki/Dorothea_Mitchell",""]);
badass.push(["Mary Ann Shadd Cary","","","img/default","https://en.wikipedia.org/wiki/Mary_Ann_Shadd",""]);
badass.push(["Ga'axstal'as, Jane Constance Cook","A Controversial Matriarch","Raising 16 kids and working as a midwife wasn't enough for Kwa'waka'wakw noble woman Ga'axstal'as Jane Constance Cook. Nope. She had some time to kill, so she developed insane communication skills by perfecting her bilingualism, studied the colonial legal systems and actively sought legal reform on local, provincial and even federal levels. For women's rights especially, Ga'axstal'as was a ga'axstal-asskicker.","img/default","http://bcbooklook.com/2014/01/11/jane-cook-crusading-matriarch/",""]);
badass.push(["Marcelle Ferron","Bold Work from a Bold Woman","One day Marcelle Ferron picked up some glass and said: \"I'm gonna make art just like everyone else's and it'll be really boring and no one will like it.\" Hahaha… no she didn't! This art school drop-out did her own thaaaang making incredible, vibrant pieces unlike anything that came before. From the metro in Montreal to the Quebec court house, sister brought colour and life to the Canadian arts. ","img/default","https://en.wikipedia.org/wiki/Marcelle_Ferron",""]);
badass.push(["Margaret Laurence","","","img/default","https://en.wikipedia.org/wiki/Margaret_Laurence",""]);
badass.push(["Julia Verlyn LaMarsh","Thank Goodness Someone's Looking After Things","Julia Verlyn LaMarsh was a federal Cabinet Minister, and Secretary of State for Canada. Which, is like, pretty cool or whatever. In the 60s, when everyone was busy getting high with flowers on their heads, she was like: \"You know what we should support? LGBTQ rights.\" And, \"You know what we shouldn't support? Tobacco smoking. It's gross.\" And, \"Also, we need Medicare.\" So many good ideas. #cabinetministerwin","img/default","https://en.wikipedia.org/wiki/Judy_LaMarsh",""]);
badass.push(["Justice Bertha Wilson","She is the Law (And She Won)","Fair, firm, and crazy awesome, little Bertha Wilson settled playground marble disputes like a friggen boss. Oh, and then emigrated to Ontario and became was the first woman appointed to the Supreme Court of Canada or whatever. Actually, wait, that's kinda important; Bertha helped bang out legislation for some super imperative issues for women, like reproductive rights and battered wife syndrome. Dang, Bertha. #ThanksGirl","img/default","https://en.wikipedia.org/wiki/Bertha_Wilson",""]);
badass.push(["Helen Irene Battle","Blinding Us with Science","A woman walks into a marine biology lab... It was Dr. Helen Battle, the pioneer zoologist. Oh you were expecting a joke there? You monster. Through years of zero-crap-taking and academic trailblazing — first Canadian woman to earn a PhD in marine biology, thank you very much — plus her groundbreaking research methods, she quietly paved the way for female scientists from coast to coast to coast.","img/default","https://en.wikipedia.org/wiki/Helen_Battle",""]);
badass.push(["Sylvia Fedoruk","Multifaceted Bossery","So, a medical hall of fame member, a curling champion and the Lieutenant Governor of Saskatchewan walk into a bar, …and she sits down. Yeah. Like, holy crap, Sylvia ¬– way to make the rest of us feel like big ol' failures. Oh wait, you're not done? You were also awarded the Order of Canada? Of course you were, Sylvia. Of course you were. ","img/default","https://en.wikipedia.org/wiki/Sylvia_Fedoruk",""]);
badass.push(["Cathleen Synge Morawetz","Riding the High Frequency Wave","Cathleen Synge Morawetz pioneered advances in partial differential equations and wave propagation math. (Don't Google that and pretend you know what it means. No one does. Except for Cathleen.) She put those concepts to work in aerodynamic, acoustic and optic fields, improving everyone's lives. She was told her family would suffer if she went to work, which is probably why she has four successful children and six grandchildren.","img/cathleen-synge-morawetz","https://en.wikipedia.org/wiki/Cathleen_Synge_Morawetz",""]);
badass.push(["Vera Peters","Just What the Vera Peters Ordered","If you, or someone you know has survived breast cancer, you might want to include Vera Peters' name in your expressions of thanks. Not only did Dr. Awesome, I mean, Vera demonstrate that specialized surgery followed by radiation was just as effective as mastectomy, she actually CURED patients with early Hodgkin's disease, a condition previously thought to be fatal. #literallifesaver #nothtecandy","img/default","https://en.wikipedia.org/wiki/Vera_Peters",""]);
badass.push(["Kim Thuy","Au revoir Vietnam, bonjour Quebec","How many overcrowded Malaysian refugee camps did you hang out in before arriving to Canada on an old-school boat from communist Vietnam, learning English and French on the fly and figuring out what in the heck is going on? Oh, none? Well Kim Thuy did that. At 10 years old. And y'know what else? She's also NICE, and a freaking TALENTED-AF, internationally acclaimed author. Just stoppit, Kim Thuy. ","img/default","https://en.wikipedia.org/wiki/Kim_Th%C3%BAy",""]);
badass.push(["C&eacute;line Galipeau","","","img/default","https://en.wikipedia.org/wiki/C%C3%A9line_Galipeau",""]);
badass.push(["Irene Uchida","Ms. Medical Mastermind","When Irene Uchida heard that people with Down's Syndrome have 47 chromosomes instead of the normal 46, she was like, \"Whoa whoa whoa WHOA.\" Then she went ahead and created Canada's first clinical cytogenetics program, discovered all sorts of other important shiz, and published over 95 scientific papers on medical science. Which, incidentally, is 95 more scientific papers than you've published. ","img/default","https://en.wikipedia.org/wiki/Irene_Uchida",""]);
badass.push(["Anna Ruth Lang","Into the Fire","There’s brave, like \"I-squished-a-huge-spider\" brave, and then there’s nuts insanity \"Anna Ruth Lang\" brave, whose car was hit by a fuel tanker truck, both falling into a river. Suffering a concussion, Anna nevertheless rescued two other passengers WHILE SWIMMING THROUGH FIERY WATERS. No wonder she was awarded the Cross of Valour, only given to Canada’s most brave. Bet she also takes care of those spiders.","img/default","https://en.wikipedia.org/wiki/Anna_Ruth_Lang",""]);
badass.push(["Jeanne Mance","Co-Founder of Montreal","Jeanne Mance co-founded the city of Montreal, literally laying foundations, and setting up its first hospital. But is she a well celebrated pioneer settler? No. Why? I'll give you a hint: it rhymes with \"shmexism.\" ANYWAYS, nurse turned nun turned tough-as-nails settler, Jeanne single-handedly saved the colony more than once, raised funds for public health and defense, and was a life-long caregiver. #CanadianHERstory","img/default","https://en.wikipedia.org/wiki/Jeanne_Mance",""]);
badass.push(["Jennie Trout","That's Dr. Trout to You","If you were suffering an illness, would you go to a doctor? Or just straight up BECOME one? In 1871, Jennie Trout became the first Canadian woman to achieve a medical license. The incredible hostility she faced from both peers and professors is enough to make you want to meat-grind a girdle, but Jennie showed those idiots. Ten years later, she helped open the Women's Medical College at Kingston.","img/default","https://en.wikipedia.org/wiki/Jennie_Kidd_Trout",""]);
badass.push(["Lucy Maud Montgomery","Girl from the Island","You: a prolific author of homespun tales set on Prince Edward Island. Us: a young nation in need of some cultural identity in the form of a delightfully plucky red-headed heroine. We smiled at each other near that house with the green gables. Haven’t been able to get you off our minds since. Meet for a raspberry cordial?","img/default","https://en.wikipedia.org/wiki/Lucy_Maud_Montgomery",""]);
badass.push(["Geraldine Moodie","","","img/default","https://en.wikipedia.org/wiki/Geraldine_Moodie",""]);
badass.push(["Sophie Morigeau","","","img/default","http://www.thefreepress.ca/news/223047531.html",""]);
badass.push(["Phyllis Munday","","","img/default","https://en.wikipedia.org/wiki/Phyllis_Munday",""]);
badass.push(["Emily Murphy","","","img/default","https://en.wikipedia.org/wiki/Emily_Murphy",""]);
badass.push(["Nahnebahwequa","This Land is My Land, For Real Tho","Nahnebahwequa earned her place in history when she went up to Queen Victoria all: \"You should probably let us own our land. Since it's already our land.\" And Vicky was all: \"Okay, but just for you 'cause racism is still kind of on-brand for us.\" In Ojibwe, Nahnebahwequa means \"upright woman,\" but a more modern translation would just be \"boss.\"","img/default","https://en.wikipedia.org/wiki/Nahnebahwequa",""]);
badass.push(["Irene Parlby","A Person's a Person No Matter How Female","Irene Parlby believed the word \"person\" should apply to um, well... persons. Even those who don't own land, or weren't born with boy-parts. The Canadian government wasn't sure though, so Irene and four of her closest person-friends appealed all the way to the British courts to get that hogwash sorted out. Then she became the first female cabinet minister in Alberta, and personed all day err'day like a boss. #girlsarepersonstoo","img/default","https://en.wikipedia.org/wiki/Irene_Parlby",""]);
badass.push(["Madelaine Parent","A Protest Powerhouse","When faced with the discrimination of others, do you sympathize? Do you give them a hug? Do you willfully go off to jail so that they can continue protesting and eventually achieve union status under the law? Hmm. I guess you just don't care. But Madeleine Parent did, about so many causes it's downright dizzying. Her heroic activism has changed the lives of countless Canadians, making her a Quebec icon.","img/default","https://en.wikipedia.org/wiki/Madeleine_Parent",""]);
badass.push(["Mona Louse Parsons","The World Needs More Monas","Mona Louse Parsons risked death and worse to shelter Allied airman in her home during WWII. (What's worse, you ask? You don't want to know.) When Mona was captured and sentenced to die, her incredibly calm demeanour surprised the judge so much, he allowed an appeal. The only Canadian female to be imprisoned by the Nazis, Mona would later be personally commended by Dwight Eisenhower for her bravery.","img/default","https://en.wikipedia.org/wiki/Mona_Louise_Parsons",""]);
badass.push(["Georgina Pope","Somebody Give that Lady a Medal","High-born Georgina Pope of P.E.I. could have married a nice dude and had lots and lots of servants to bring her cucumber sandwiches. Instead, she decided \"Nope, I'ma go be a nurse in an uncomfortable climate where there's too many sick people and not enough food. Mhmm, yep that sounds good.\" For her relentless efforts in South Africa, she was the first woman awarded the Royal Red Cross in 1903. ","img/default","https://en.wikipedia.org/wiki/Georgina_Pope",""]);
badass.push(["Nellie Yip Quong","No-nonsense Nellie","Nellie Yip Quong spoke 5 Chinese dialects and advocated for Chinese rights in Vancouver …and she wasn't Chinese. In 1900 Nellie \"Towers\" was disowned by her family after scandalously marrying Charlie Yip Quong. Nellie felt that the Canadian government's withholding of services to the Chinese community was racist (yep), so girlfriend just did it all herself. Translator, broker, midwife and law challenger – Nellie knew what was up.","img/default","https://en.wikipedia.org/wiki/Nellie_Yip_Quong",""]);
badass.push(["Fabienne Larouche","","","img/default","https://fr.wikipedia.org/wiki/Fabienne_Larouche",""]);
badass.push(["Kate Rice","I Am Sayin' She's a Gold Digger","Some people are so many awesome things it's downright annoying. Kathleen Creighton Starr Rice (<-- name goals) was a mathematics professor, a mountaineer, a \"new frontier\" homesteader, and a successful prospector. She taught herself geology, hunting, trapping and the Cree language all on her own. (Pfffft, easy.) For some reason, this blonde, six-foo-tall prospecting wonder was always being followed by the pesky press...","img/default","https://en.wikipedia.org/wiki/Kate_Rice",""]);
badass.push(["L&eacute;a Roback","A Relentless Reformer","L&eacute;a Roback thought that injustices like racism and violence were like, you know, bad. After realising that the morons around her didn't share her totally justifiable outrage, she vowed to devote her life to social activism. L&eacute;a fought for access to free and safe abortion, better housing, education and a million other things, so that today we can sit here watching cat videos and not getting dumped on by prejudice. ","img/default","https://en.wikipedia.org/wiki/L%C3%A9a_Roback",""]);
badass.push(["Marie Marguerite Rose","A Free Agent","Marie Marguerite Rose was a Guinea born woman sold into slavery for 19 years, and emancipated in 1755. (Tell me again how hard your day was... ?) Once free, Marie married an emancipated Mi'kmaw man, and despite horrendous racism and sexism, opened a tavern near the barracks of Louisbourg, Nova Scotia. A dark-skinned, interracial couple mingling with other business owners and demanding the same rights? Um, yes. Yes that exactly. ","img/default","https://en.wikipedia.org/wiki/Marie_Marguerite_Rose",""]);
badass.push(["Gabrielle Roy","Take a Hard Look in the Mirror","Remember that time when, while earning your living doing something totally different, you wrote a novel on the side that inspired Quebec's Quiet Revolution of the 1960s? No? Oh, my bad. I'm confusing you with critically acclaimed Francophone author Gabrielle Roy. You know, one of the most significant writers of psychological realism in the history of Canadian literature? Sorry - you probably get that all the time. ","img/default","https://en.wikipedia.org/wiki/Gabrielle_Roy",""]);
badass.push(["Idola St-Jean","Extend the Franchise. Period.","In 1927 Idola St-Jean and her lady squad went to visit Quebec Premier Louis-Alexandre Taschereau all: \"Here's what's going to happen here. You're going to extend the vote to women, we're going to enjoy equal representation, and I don't wanna hear no lip. Cool? \"Taschereau was like: \"Hmmmmm... nah.\" So, professor, journalist and suffrage pioneer Idola came back every year until 1940, when the next premier said \"Ok. Cool.\"","img/default","https://en.wikipedia.org/wiki/Idola_Saint-Jean",""]);
badass.push(["Catherine Schubert","I'm Coming with You, End of Discussion.","In 1862, when her husband decided to follow the gold prospectors to British Columbia, Catherine Schubert was like, \"Ohhhhh heck no. You think you're leaving me here with three little kids?\" So, four-months-pregnant Catherine packed up her children (5, 3 and 1), and travelled west through fricken freezing, treacherous surroundings. Lady went into labour on a RAFT and became the first woman ever to enter B.C. by land.","img/catherine-shubert","http://www.cbc.ca/archives/entry/catherine-schubert-crosses-the-rockies-in-1862",""]);
badass.push(["Laura Secord","This Petticoat was Made for Walkin'","Laura Secord didn't bust out the pedometer when it was time to walk 32 kilometers through the middle of the War of freakin' 1812. She just hiked up her skirt, kicked rocks through the Canadian wilderness and told the British: \"Just for your FYI, the Americans are coming and also I'm a war hero now. Kthxbye.\"","img/default","https://en.wikipedia.org/wiki/Laura_Secord",""]);
badass.push(["Lise Payette","","","img/default","https://en.wikipedia.org/wiki/Lise_Payette",""]);
badass.push(["Mary Ann Shadd","First Female Publisher in Canada","Mary Ann Shadd was a black, female newspaper editor in 1850, and holy crap, I can't believe I just wrote that. Like!? Ok sorry, focusing, focusing: Mary used her paper, the Provincial Freeman to uplift and unite African Americans and Canadians, enforce the importance of education, and empower her community to fight back against racist perceptions. With zero formal training and no journalism experience, I just. Wow.","img/default","https://en.wikipedia.org/wiki/Mary_Ann_Shadd",""]);
badass.push(["Norma Shearer","","","img/default","https://en.wikipedia.org/wiki/Norma_Shearer",""]);
badass.push(["Hide Hyodo Shimizu","Schooled Xenophobia","Why does Hide Hyodo Shimizu have the Order of Canada and you don't? Because she went to Ottawa to go: \"Give me the vote you dusty old racists\"? Because she was the first Japanese-Canadian to get a teaching certificate in BC? Or because she taught in Japanese internment camps before being interned herself? No. Because ALL those things. ","img/default","http://www.torontonajc.ca/2014/02/16/hide-shimizu-memorial-scholarship/",""]);
badass.push(["Angela Sidney","","","img/default","https://en.wikipedia.org/wiki/Angela_Sidney",""]);
badass.push(["Elizabeth Lawrie Smellie ","Matron-in-Chief","\"Ew, blood!\" said Dr. Elizabeth Smellie never. After patching up the WWII wounded, Elizabeth hit up McGill University to teach another generation of nurses how to kick ass. You know… medically speaking. After that, in competition only with herself, Lizzy served as the first female colonel in the Canadian army as the medical corps' matron-in-chief in WWII. Yeah, \"matron-in-chief.\" AKA: Lady. Boss.","img/Elizabeth-smellie","https://en.wikipedia.org/wiki/Elizabeth_Lawrie_Smellie",""]);
badass.push(["Ethel Stark","Female Soloist #sorrynotsorry","Not that long ago, women were virtually banned from orchestras. Because, you know, our lady hands and lady lungs just… can’t, it’s… so, hard, (It’s all the same.) Ethel Stark saw this nonsense for what it was, and became not only a boss violinist, but the first woman to conduct an orchestra at Carnegie Hall, and the first female artistic director of a Canadian symphony orchestra. BAM.","img/default","https://en.wikipedia.org/wiki/Ethel_Stark",""]);
badass.push(["Emily Stowe","No Time for Small Minds","In 1865, the Vice President of the Toronto School of Medicine refused Emily Stowe admission, with this little nugget of wisdom: \"The doors of the University are not open to women, and I trust they never will be.\" Sounds like a great guy, eh? So Emily Stowe said some choice words to him and went to study medicine in the States, before returning to TO and opening her own practice.","img/default","https://en.wikipedia.org/wiki/Emily_Stowe",""]);
badass.push(["Chantal Peticlerc","Give Her the Gold and Shut Up","Chantal Petitclerc wins at everything. Probably including things you can’t even win at, like meditation. This Senator from Quebec (nbd…) has won more medals than any other women in the Paralympic Games, 1992–2008. Oh yeah, competitive boss lady lost the use of her legs as a child, but do you think that slowed her down? Chantal, I’m a little afraid of you, but also impressed AF.","img/default","https://en.wikipedia.org/wiki/Chantal_Petitclerc",""]);
badass.push(["Thanadelthur","Not Lost in Translation","Chipewyan Thanadelthur, born 1697, was captured by Cree in 1713. Unimpressed, clever Thanadelthur escaped, only to be found by the Hudson’s Bay Company. Annoyed by her terrible luck but hoping to get back to her people, she agreed to negotiate a peace agreement between Chipewyan and Cree. Sister negotiated and translated like a boss, BAM! Agreement. Ask me if she received payment for her work. Go ahead. Ask me. ","img/default","https://en.wikipedia.org/wiki/Thanadelthur",""]);
badass.push(["Maud Watt","Angel of Hudson Bay","When the over-hunting of beaver threatened to collapse both the northern Quebec European and Cree economies, James Watt asked his wife, Maud, if she could help. By \"help\" he meant: \"K, I just need you to cross the frozen bay by dog sled with our two small children in -45, train to Quebec City and convince them to set land aside for a preserve.\" Maud was like, \"FFS, James. Yes.\" ","img/default","http://www.hbcheritage.ca/hbcheritage/history/people/women/maudwatt",""]);
badass.push(["Simonne Chartrand","Leader of Women and Men","Some people have a calling. Some people have alllll the callings. Simmone Chartrand actively supported feminism and human rights, as well as labour and union rights, all with a pacifist approach Celebrated author, media personality and mother of seven, Simmone doesn’t care that her numerous achievements make me feel like a failure, but she does care about basically everything else, making her a champion of modern activism in French Canada. ","img/default","https://en.wikipedia.org/wiki/Simonne_Monet-Chartrand",""]);
badass.push(["Madelaine Redfern","Receive, Give back, Rock on.","Madeleine Redfern said it right: \"Community empowerment rocks!\" YEAH it does! And you know what else rocks? You, Madeleine. As the current Mayor of Iqaluit and the first Inuk (male or female) to clerk at the Supreme court, you equip your community to become better, while challenging the historical chronicling of the Eastern Arctic Inuit as executive director of the Qikiqtani Truth Commission. ","img/default","https://en.wikipedia.org/wiki/Madeleine_Redfern",""]);
badass.push(["Janette Bertrand","Woman of the Century","Sometimes, women become writers. Other times, women become writer/actor/educator/radio-host …ers. And also they’re born in 1925 Quebec. And their name is Janette Bertrand, and they’re amazing. On a related note: Janette Bertrand, who is amazing, received the Prix Condorcet, an award given each year to a public figure who has contributed to freedom of conscience in Quebec. What a coincidence.","img/default","https://en.wikipedia.org/wiki/Janette_Bertrand",""]);
badass.push(["Dr. Alis Kennedy","An Outstanding Ontarian","Activist, M&eacute;tis leader, and founding member of the Centennial College Aboriginal Studies Council, we're pretty sure Senator Dr. Alis Kennedy never sleeps. The first Indigenous woman to get a commercial pilot's license, Alis continues to work for so many causes it's baffling. There's an Alis for the Pan Am Games, an Alis for girls' education, an Alis for protecting big endangered cats (for real), and like, 1000 other Alis's. ","img/default","http://www.metisnation.org/news-media/news/m%C3%A9tis-senator-receives-ontario-medal-for-good-citizenship/",""]);
badass.push(["Tanya Tagaq","An Inuk Inspiration","Think you can do what Tanya Tagaq can? Depends: are you an Inuk Canadian who pioneered her own form of solo throat singing, a style usually only achievable with two singers? Good for you! Now all you've got to add is being a killer solo act who's also collaborated with international artists like Björk and earn the Order of Canada Member in 2016. Still there? Hello?","img/default","https://en.wikipedia.org/wiki/Tanya_Tagaq",""]);
badass.push(["Buffy Saint&eacute;-Marie","The Blacklist Slayer","Buffy Saint&eacute;-Marie has a doctorate in getting in everyone's comfortable faces. (Actually, it's in fine arts, but she's still Dr. Saint&eacute;-Marie). They tried blacklisting her on the radio, so she went: \"How about I just rock being an iconic folk singer and native activist for four decades?\" Plus she co-wrote \"Up Where We Belong,\" which I'M NOT CRYING YOU ARE","img/buffy-sainte-marie","https://en.wikipedia.org/wiki/Buffy_Sainte-Marie",""]);
badass.push(["Lily Singh","","","img/default","https://en.wikipedia.org/wiki/Lilly_Singh",""]);
badass.push(["Angela James","Ice Breaker","Angela James has been named the National Women's Hockey League's Most Valuable Player six times, is openly gay, and of black heritage. Guess which one of those three facts is relevant to her career? After an offended father banned young Angela from playing hockey because she was better than his son, her mother put her in more senior teams, where she took on older girls and won. H8ters, you're benched.","img/default","https://en.wikipedia.org/wiki/Angela_James",""]);
badass.push(["Jean Augustine","Do You Know Why You Were Sent Here Today, Canada?","Know why you don't want to be sent to the principal's office in school? Because they see right through your crap excuses, and set you straight. Well, former principal Jean Augustine thought Canada needed a little metaphorical kick to the behind, so she became a Liberal member of the House of Commons, the first African Canadian woman to be elected as such. And duh, Ladyboss set everybody straight.","img/default","https://en.wikipedia.org/wiki/Jean_Augustine",""]);
badass.push(["Anne Cools","","","img/default","https://en.wikipedia.org/wiki/Anne_Cools",""]);
badass.push(["Frances Oldham Kelsey ","Thalidomide Slayer","If a powerful pharmaceutical company came to you and said: \"All the cool countries are doing it…\" would you step up and go: \"Hold up, though\"? The FDA's Frances Oldham Kelsey sure as hell did. She told the makers of thalidomide where they could shove it, and she didn't mean orally. She protected kids, she kicked butt, she even shared the credit.","img/default","https://en.wikipedia.org/wiki/Frances_Oldham_Kelsey",""]);
badass.push(["Carol Huynh","The Woman with the Golden Hold","Throwing opponents to the mat? Boss. Winning Canada's first-ever Olympic gold medal in wrestling? Bosser. Oh, and Carol Huynh figured she'd pick up a bronze medal at the next one too. NBD. Her whimpering rivals don't have to look far for guidance: her master's degree in counselling psychology oughtta do the trick.","img/default","https://en.wikipedia.org/wiki/Carol_Huynh",""]);
badass.push(["Samantha Bee","Comedy's Queen Bee","Samantha, girl... thanks for cutting through the bull. On Full Frontal With Samantha Bee, bigots, chauvinists, wingnuts and liars all suffer the same fate under her hilariously unimpressed \"ORLY\" glare. Full Frontal deals with feminist and political issues as they deserve: with clever, categorical mockery. Mess with the Bee, you gonna get stung.","img/default","https://en.wikipedia.org/wiki/Samantha_Bee",""]);
badass.push(["Adrienne Clarkson","Her Excellency, The Right Honourable Madam Slayer.","When Hong Kong-born, Adrienne Louise Clarkson n&eacute;e Poy (Chinese: 伍冰枝 ) arrived as a refugee from Japanese-occupied China, she hoped for a better life. So, naturally, she earned a number of university degrees, became a producer and broadcaster for CBC, became a stateswoman to serve as Governor General of Canada, and was sworn into the Freakin' Queen's Privy Council. SO. Better life? Check.","img/default","https://en.wikipedia.org/wiki/Adrienne_Clarkson",""]);
badass.push(["Michaëlle Jean","Former GG, Cool AF","As non-idiots already know, refugees make our country better. Want proof? Watch Michaëlle Jean come over from Haiti, rise through the CBC until they went ahead and named a show after her, then get tapped to be the queen's #1 wing lady. And how's our former governor-general spending retirement? She's secretary-general of the Organization internationale de la Francophonie, AKA: total dur à cuire.","img/default","https://en.wikipedia.org/wiki/Micha%C3%ABlle_Jean",""]);
badass.push(["Samantha Nutt","","","img/default","https://en.wikipedia.org/wiki/Samantha_Nutt",""]);
badass.push(["Sheila Watt-Cloutier","Just Saving the Earth Over Here, NBD.","Sheila Watt-Cloutier doesn't wake up, send a few emails and say, meh, now Imma take a nap. Nope. She aims big. Really big. Like the actual entire world big. This Inuit boss activist has been nominated for a Nobel Peace Prize for outlining the impact global climate change has on human rights. (Sounds important? That's cuz it is.) When the world DOESN'T melt, we'll be like: thanks, Sheila.","img/default","https://en.wikipedia.org/wiki/Sheila_Watt-Cloutier",""]);
badass.push(["Alice Munro","The Fantastic and Ordinary Lives of Girls and Women","Where would be without art? Where would we be without Alice Munro? Oh GOD STOP I don't like to think about it. Alice's masterful architecture and astounding imagination mean we get to read fiction that celebrates nuance, plays with time, explores the human condition and rewards empathy. Basically: genius Alice makes you laugh, makes you cry, and makes you think: an act others never fail to undervalue.","img/default","https://en.wikipedia.org/wiki/Alice_Munro",""]);
badass.push(["Margaret Atwood","The Readable Woman","How do you take your literary feminism? Margaret Atwood serves it up: hot and fresh. You want some reflection on gender roles? BAM! The Edible Woman. Dystopian science fiction? KAPOW! The Handmaiden's Tale. Or, heck, a comic about a catman? BOOM! Angel Catbird. And if you're not hungry for reading, just watch her school a braying, populist dink about the importance of public libraries. Mmm! Delicious.","img/default","https://en.wikipedia.org/wiki/Margaret_Atwood",""]);
badass.push(["Sarah Polley","National Treasure to the Max","Actor, director, writer, activist – Sarah Polley turns being a Canadian Icon up to eleven. (Seriously, ask anyone above the 49th.) Child stardom might have been enough for some other losers, but Sarah Polley asked herself one question: \"Is there anything I can't do?\" The answer? \"lol, nope.\"","img/default","https://en.wikipedia.org/wiki/Sarah_Polley",""]);
badass.push(["Hayley Wickenheiser","Wickenheiser FTW. (All of Them.)","Team Canada captain and overall Boss Lady Hayley Wickenheiser is glittery AF. With GOLD MEDALS! That's how it goes when you're the best female hockey player in history, and are tied only with your teammates, Caroline Ouellette and Jayna Hefford for most gold medals of any Canadian Olympian. Wickenheiser's gender is awesome, duh, but also immaterial to her success as an athlete. Because, oh that's right: women are people too. ","img/default","https://en.wikipedia.org/wiki/Hayley_Wickenheiser",""]);
badass.push(["Caroline Ouellette","","","img/default","https://en.wikipedia.org/wiki/Caroline_Ouellette",""]);
badass.push(["Nadine Caron","Winning at Being First","Nadine Caron isn't always first, but …no wait, no actually she is. First in her class, first choice doctor; heck, Nadine's the first Canadian female general surgeon of First Nations descent. Girlfriend's even got some first place athletic awards under her belt because yeah sure why not. Jealous of her glittering golds? You're not the first.","img/default","https://en.wikipedia.org/wiki/Nadine_Caron",""]);
badass.push(["Kristine Stewart","140 Characters of Boss","Kirstine Stewart authored a book on female leadership titled “Our Turn” in 2013. That’s weird because it’s not like former VP of Media for Twitter North America or CBC Executive Director of programming had any experience leadioh. Currently Chief Strategy Officer at Diply, Kirstine knows what's up in the business world, and makes sure other young ladies know they can know that, too. ","img/default","https://en.wikipedia.org/wiki/Kirstine_Stewart",""]);
badass.push(["Attiya Khan","We Are Not Asking \"Why,\" We Are Asking: \"How Can We Help?\"","Instead of drop-kicking the face of her former abusive boyfriend into a river extra-stingy lava, Toronto’s Attiya Khan took the (alright, fine) super high road and asked him if he wanted “to talk.” Incredible, brave and innovative Attiya is making a film about it, in order to shed light on the “intolerably high” rate of violence against women in Canada, and everywhere. ","img/default","http://www.macleans.ca/news/canada/i-think-some-men-who-use-violence-can-change/",""]);
badass.push(["Lucy Decoutere","Speak Your Truth","Whether you know her as Lucy from Trailer Park Boys, captain Decoutere in the Royal Air Force or as Lucy, the first woman to publicly allege former Radio Host Jian Gomeshi of sexual assault, Lucy Decoutere is all kinds of #bold. Lucy braved public defamation to fight for what she believed in, and even after hearing an unsatisfactory verdict, she remains heroic, and funny as hell. #imwithher","img/default","https://en.wikipedia.org/wiki/Lucy_DeCoutere",""]);
badass.push(["k.d.lang","A Constant Craving For Not Giving a F.","k. d. lang is the powerful lady she is and if you aren’t on board with that, you can legit GTFO. Incredibly tallented and hugely inspirational, k.d. braved coming out to the country music industry 1993, and, even more controversially, as a proselytising vegetarian in 1990. After being banned on dozens of radio stations do you think k.d. backed down? … Do you?","img/default","https://en.wikipedia.org/wiki/K.d._lang",""]);
badass.push(["Joni Mitchell","\"A Painter Derailed by Circumstance\"","Roberta Joan Mitchell is one of the greatest song writers of all time. Period, thank you, we’re done here, goodnight. Somehow wise on all things – from art, to motherhood, to the passing of time – Joni puts her finger on the human condition so beautifully and acutely, her soprano/contralto voice became that of a generation. Joni: self-taught musician, beautiful soul, woman made to inherit the earth.","img/default","https://en.wikipedia.org/wiki/Joni_Mitchell",""]);

function make() {
    // replaces elements in layout with a random person from the badass array
    document.getElementById("badassName").innerHTML = badass[randomNumber][0];
    document.getElementById("badassSub").innerHTML = badass[randomNumber][1];
    document.getElementById("badassBio").innerHTML = badass[randomNumber][2];
    document.getElementById("badassLink").setAttribute("href", badass[randomNumber][4]);
    if (window.matchMedia("(min-width: 750px)").matches) {
        if (badass[randomNumber][5]) {
            document.getElementById("badassPerson").style.backgroundImage = "url(" + badass[randomNumber][3] + "-dark-big.jpg)";
        }else{
            document.getElementById("badassPerson").style.backgroundImage = "url(" + badass[randomNumber][3] + "-big.jpg)";
        }
    } else {
        if (badass[randomNumber][5]) {
            document.getElementById("badassPerson").style.backgroundImage = "url(" + badass[randomNumber][3] + "-dark-sml.jpg)";
        }else{
            document.getElementById("badassPerson").style.backgroundImage = "url(" + badass[randomNumber][3] + "-sml.jpg)";
        }
    }

    if (badass[randomNumber][5]) {
        document.getElementById("badassPerson").classList.remove('light');
        document.getElementById("badassPerson").classList.add('dark');
        document.body.style.backgroundColor = "black";
    } else {
        document.getElementById("badassPerson").classList.add('light');
        document.getElementById("badassPerson").classList.remove('dark');
        document.body.style.backgroundColor = "white";
    }
}

function next() {
    randomNumber++;
    make();
}

function rando() {
    randomNumber = Math.floor(Math.random() * badass.length);
    make();
}


//==============================================================
//PRIMARY FUNCTION (EXECUTES WHEN PAGE IS LOADED)
//==============================================================

document.addEventListener('DOMContentLoaded', function (event) {

    rando();
    document.getElementById("random").addEventListener("click", rando);

    //DEBUG
    // next();
    // document.getElementById("bold_logo").addEventListener('click', next);

});