var oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds
var firstDate = new Date(2017, 2, 9);
var currentDate = new Date();

var randomNumber = Math.ceil((currentDate.getTime() - firstDate.getTime()) / oneDay);
console.log(randomNumber);

//==============================================================
//BADASSES
//==============================================================

var badass = new Array();
// data format for badasses: name (0), nickname or sub-head (1), link (2), short bio (3), image (4)
badass.push(["Maude Abbott","The Heart of the Matter","I'll give you three guesses why super-genius Maude Abbot was rejected by McGill University in 1886. You're only going to need one. As the first in a series of epic eye-rolls followed by delicious victories, Maude later became the first woman to receive a B.A. from McGill under a full scholarship, and became a world authority on life-saving heart surgery. But, you know, probably women shouldn't go to university.","img/maude-abbott","https://en.wikipedia.org/wiki/Maude_Abbott","dark"]);
badass.push(["Mary Electa Adams","Badass Chief Preceptress ","Mary Adams held the radical belief that women &mdash; wait for it &mdash; have brains. Mary traveled all over talking this crazy talk before becoming \"Chief Preceptress,\" (read: \"Boss Lady\") of a school in Sackville, New Brunswick and completely reforming their crap female education programs. Mary felt like, in addition to learning to read the Bible, women could benefit from studying, say, science, mathematics, moral philosophy and Latin. YEP!","img/mary-electa-adams","https://en.wikipedia.org/wiki/Mary_Adams_(educator)",""]);
badass.push(["Emma Albani","Qu&eacute;b&eacute;cois Idol","When Emma Albani discovered professional singing was a distasteful career for a woman, she said: \"Okay, I'll just be a nun.\" Pffffft. JK! As a teenager with pipes that'd make Simon Cowell weep, Emma moved to New York and worked odd jobs to afford continuing her musical education. At her debut performance, fans threw LIVE DOVES at her FACE (which, turns out, is a good thing).","img/default","https://en.wikipedia.org/wiki/Emma_Albani","dark"]);
badass.push(["Maud Allan","Lewd Lesbian in London","For Maud Allan, \"bold,\" doesn't even come close. Musician, dancer, choreographer and unapologetic social-norms-challenger, in 1918 Maud sued the small-minded MP who accused her of sexual perversion (same guy who thought homosexuals were secretly behind WWI... yeah) in a sensational trial that drew much-needed attention to freedom of expression and the arts. Maud lost the trial, but you don't see us celebrating Mr. Jerkface MP a century later.","img/default","https://en.wikipedia.org/wiki/Maud_Allan","dark"]);
badass.push(["Anna Mae Aquash","Advocacy for Anna","As people with functioning brains already know, fighting to correct blatant prejudice and inequality is a &mdash; wait for it &mdash; GOOD thing, and should be encouraged. Influential Mi'kmaq activist Anna Mae Aquash never got the chance to live her potential. With two small daughters at home, Anna was murdered on account of her strong voice. Anna knew that change was possible. Let's not let her down.","img/default","https://en.wikipedia.org/wiki/Anna_Mae_Aquash","dark"]);
badass.push(["Edith Jessie Archibald","Socialite General","With a knack for rallying folks to her cause, Edith Jessie Archibald spent 30 freakin' years fighting for equality in education, better healthcare and &mdash; oh yeah &mdash; the right for Nova Scotia women to straight up VOTE. In 1917, she helped win that right, all while leading The Red Cross' outreach for prisoners of war because multi-tasking, NBD.","img/edith-jessie-archibald","https://en.wikipedia.org/wiki/Edith_Archibald",""]);
badass.push(["Elizabeth Arden","Maybe She's Born with It","Florence Nightingale Graham &mdash; wait, who? &mdash; landed a job as a \"treatment girl\" before debuting a new name and salon in 1910. Elizabeth did today's cosmetic stars a solid by teaching women how to apply makeup and making it socially respectable to wear day-to-day. Lady boss hired chemists to produce her youth-promising creams, and took that shiz to the bank. Florence, Lizzy &mdash; don't matter. Sister died a millionaire.","img/elizabeth-arden","https://en.wikipedia.org/wiki/Elizabeth_Arden","dark"]);
badass.push(["Helen Armstrong","Wild Woman of the West","Helen Armstrong believed that women should be paid the same as men for the work that they do. Oh, and that they shouldn't need to ask for that, because DUH. Helen's campaigning skills were top shelf, but girlfriend never gets enough credit for the mountains she moved. Helen, thanks for picketing at 5 AM when you had small children at home so your sisters could feed their own. #respect","img/default","https://en.wikipedia.org/wiki/Helen_Jury_%E2%80%9CMa%E2%80%9D_Armstrong","dark"]);
badass.push(["Kenojuak Ashevak","Girl From The North Country","Put this lady on a stamp! Oh, you already did that. Right. Good job. Make her an Officer of Order of Canada! Give her honourary doctorates! HERITAGE MINUTE! Oh &mdash; check, check and check. This pioneer of modern Inuit art became one of Canada's most beloved artists whose talent was balanced by intrinsic authenticity and humility. No jokes here, she was a hero.","img/default","https://en.wikipedia.org/wiki/Kenojuak_Ashevak","dark"]);
badass.push(["Elizabeth Bagshaw","She Did It Her Way","Elizabeth Bagshaw persevered through threatening (and idiotic) public scorn to provide desperately needed medical care in Canada's first illegal birth control clinic. That's so bold and brave I can't even make a joke about it. Elizabeth lived her whole life progressively, not giving half a crap if people disapproved, and died a centurion member of the Order of Canada.","img/default","https://en.wikipedia.org/wiki/Elizabeth_Bagshaw","dark"]);
badass.push(["Mary \"Bonnie\" Baker","There's No Crying","The All-American Professional Baseball League. Ever heard of it? How about the woman the press called \"Pretty Bonnie Baker,\" but who the scorecard called: Pro-AF Boss Lady. (Perhaps their wording was different, it's whatever.) After 930 games of butt-kicking, and serving as the league's first and only female player-manager, \"Pretty Bonnie\" casually transitioned into the role of first female sports broadcaster in Canada.","img/default","https://en.wikipedia.org/wiki/Bonnie_Baker","dark"]);
badass.push(["Frances Barkley","Superstition Overboard","A woman aboard? Blasphemy! Though, this was back in the day when scurvy was God's punishment for laziness, and bonnets were scandalously sexy. So. What's a woman desperate for the deep blue to do? Disguise herself as a man! Or she could pull a Frances Barkley: marry a sea-captain, and tag along to become the first woman ever to see Canada's west coast, and circumnavigate the world &mdash; undisguised.","img/default","https://en.wikipedia.org/wiki/Frances_Barkley","dark"]);
badass.push(["Robertine Barry","Mightier than the Sword","Robertine Barry thought marriage was nice and all, but wasn't \"the goal to which must be devoted a lifetime of noble efforts.\" Professional journalism on the other hand: heck yeah! Through scorn and reprimand, Barry became the first woman hired full time by a Quebec paper. Years later, Barry's own journal, Le Journal de Françoise, granted other sister writers their big breaks. ","img/default","https://en.wikipedia.org/wiki/Robertine_Barry","dark"]);
badass.push(["Margaret Benedictsson","Immigrant Strong","Next time you can barely make it through writing a status update because, \"it's cold in here, you guys,\" remember that Margret Benedictsson was a broke, parentless kid in NORTHERN ICELAND who picked up to Canada and published Freyja/Woman (the only suffrage magazine at the turn of the century and ps., it was hugely successful) out of MANITOBA. Still cold? Please.","img/default","http://www.thecanadianencyclopedia.ca/en/article/margret-benedictsson/","dark"]);
badass.push(["Myra Bennett","\"The Nurse\"","So the English nursing recruiter was like: \"Myra! Heeyyy Girl. How's not freezing to death going? Yeah that's good. Sooo I was just wondering&hellip; see, there's these isolated Newfoundland communities LET ME FINISH, MYRA and like, well, it's basically desolate af, and um&hellip; how about you go be their only nurse? And Myra was like \"Hmmm ok!\" and proceeded to deliver about 5,000 babies and pull over 3,000 teeth.","img/default","https://en.wikipedia.org/wiki/Myra_Bennett","dark"]);
badass.push(["Mary Bibb","Freedom Fighter","As a pretty excellent example of the pen being mightier than the sword. In 1851 Mary Bibb began publishing The Voice of The Fugitive, the first anti-slavery newspaper made in Canada by people of African descent. Mary and her husband Henry devoted their lives to equal education and settlement for freedom-seekers coming to Canada, making 1: huge strides for racial equality in Canada, and 2: my life seem easy-af.","img/default","https://en.wikipedia.org/wiki/Mary_E._Bibb","dark"]);
badass.push(["Lucie Blackburn","Give Me One Reason to Stay Here","When Lucie and her husband fled to Michigan to escape slavery, the D-bag slave hunters tracked them down for recapture. Lucie was like \"UGH not this crap again,\" and escaped again, yelling \"BOYS BYE\" all the way to Canada. The Blackburns began Toronto's first taxi business and helped build the city's oldest standing church. Canada was like, \"Umm, these two are great.\" Thereafter vowing not to return escaped slaves.","img/default","http://www.pc.gc.ca/APPS/CP-NR/release_e.asp?bgid=503&andor1=bg","dark"]);
badass.push(["Fern Blodgett","A Decorated Marine","Little Fern Blodgett grew up in Ontario watching ships on the great lakes and was like, \"Imma sail one of those one day!\" And her parents were all: \"But Fern, you're a girl.\" And Fern looked at them very seriously and replied, \"I SAID, I'm going to SAIL ONE OF THEM FANCY SHIPS.\" And wouldn'tcha knowit? Baby Fern became the first Canadian woman to serve in the Merchant Marines.","img/default","http://www.thewhig.com/2015/03/03/international-womens-day-fern-blodgett-sunde-a-warships-wireless-officer","dark"]);
badass.push(["Esther Brandeau","The First Jewish Girl in Canada","Esther Brandeau lied about basically everything that matters just to see the magical place they call Canada. Makes ya feel special, eh? Disguised as a boy and denying her religion, Esther hung out on the St. Michel en route to New France before both her gender and Judaism were discovered (oops). When faced with Catholic conversion (\"C'mon, Esther. All your friends are doing it.\") Esther decided \"&hellip;nah,\" and was deported. ","img/default","https://en.wikipedia.org/wiki/Esther_Brandeau","dark"]);
badass.push(["Roberta Bondar","When I Grow Up, I Want to Be a Roberta Bondar","Roberta Bondar has 22 honorary degrees. I could stop right here, but just for kicks let's keep going. First Canadian woman in space, (not bad, I guess), received the Order of Canada (yep, mmhmm), and was inducted into the Canadian Medical Hall of Fame because she's also a freakin' neurologist. You know, a brain doctor. IT'S WHATEVER, THO, ROBERTA; leave some awesome for the rest of us mmkay?","img/roberta-bondar","https://en.wikipedia.org/wiki/Roberta_Bondar","dark"]);
badass.push(["Marguerite Bourgeoys","That Lady was a Saint. No, Seriously.","Marguerite Bourgeoys saved orphans and educated the poor regardless of their gender or heritage. Sound saint-like? The Pope thought so, too. St. Marguerite also really, reeeeeally wanted to teach outside the convent, taking three separate trips to France in the 1600s to convince the local bishops. After getting her wish, Marguerite turned her saint-ness up to 11, establishing schools and saving people from death. (NBD.)","img/default","https://en.wikipedia.org/wiki/Marguerite_Bourgeoys","dark"]);
badass.push(["Molly Brant","When Molly is Speaking, You Are? That's Right: Listening","A leader in matriarchal Iroquois society, a consort of Sir William Johnson and a superintendent for Northern Indigenous Affairs, Molly Brant had so much influence it's legit nutsballs. So much, in fact, that A MAN in the 18th century had this to say: \"One word from her is taken more notice of by the Five Nations than a thousand from any man without exception.\" Can girlfriend get a slow clap??","img/default","https://en.wikipedia.org/wiki/Molly_Brant","dark"]);
badass.push(["Harriet Brooks","First Canadian Female Nuclear Physicist ","Harriet was a BA with a BA &mdash; in mathematics and natural philosophy &mdash; but lady friend didn't stop there. Harriet told that glass ceiling to back the F up, and became the first woman at McGill to receive a master's degree in electricity and magnetism. (Sounds important.) Then she went ahead and discovered the recoil of a radioactive atom sounds importanter) and was an all-around BOSS.","img/default","https://en.wikipedia.org/wiki/Harriet_Brooks","dark"]);
badass.push(["Rosemary Brown","Brown is Beautiful","Rosemary Brown received 15 honorary doctorates from Canadian universities. *Drops the mic.* FIFTEEN. Why? Let's explore: first black female member of a provincial legislature. First woman to run for leadership of a federal political party. Founding member of the Vancouver Status of Women Council. CEO of advocacy group MATCH International Women's Fund. Chief commissioner of the Ontario Human Rights Commission. Rosemary! Dang, girl. You killin' it. ","img/default","https://en.wikipedia.org/wiki/Rosemary_Brown_(politician)","dark"]);
badass.push(["Emily Carr","Becoming a National Icon","Some people (you) are described as Canadian. Other people (not you) are described as inspiring Canadian icons. But don't worry, there's totally hope! All you've gotta do is: represent the national imagination through incredible innovative art, win a couple writing awards, succeed against basically all odds and have a bunch of institutions named for your bravery. So like, probably get going on that.","img/emily-carr","https://en.wikipedia.org/wiki/Emily_Carr",""]);
badass.push(["Th&eacute;r&egrave;se Casgrain","A Force to be Reckoned With","When the Quebec government told T&eacute;r&egrave;se Casgrain she wasn't allowed to vote, she was like, \"Aw, sweetie. It's so cute that you think that!\" Then she hosted a feminist radio show, became the first female leader of a Canadian political party, helped found the League for Human Rights and became a freaking SENATOR. Oh, and cast a few delicate lady votes with her delicate lady fingers.","img/therese-forget-casgrain","https://en.wikipedia.org/wiki/Th%C3%A9r%C3%A8se_Casgrain",""]);
badass.push(["Ethel Catherwood","The \"Prettiest Girl\" at the Games","Ethel Catherwood was a kickass, gold-medal winning Saskatoonian who didn't give two hoots about other people's dumb opinions. After killin' it at the 1928 Olympics, Ethel got secretly married and divorced in Reno, while the press were all \"BUT ETHEL!\" and Ethel was like, \"You know what, I don't do interviews.\" This athletic goddess brought home what is still Canada's only track-and-field female gold. Ethel. Saskatchewan Sports Hall-of-Famer.","img/default","https://en.wikipedia.org/wiki/Ethel_Catherwood","dark"]);
badass.push(["Victoria Cheung","A Mission Not Impossible","Born in Canada and trained as a physician, second-generation Chinese-Canadian Victoria Cheung moved to China in 1923 to work as a missionary. When WWII hit and everyone was getting the heck outta dodge, Vicky was like \"I ain't scared,\" and kept on treating patients with renewed vigour. A strong, independent woman who don't-need-no-man, Victoria never married, later adopting a child to raise solo.","img/default","http://chinatown.library.uvic.ca/node/860","dark"]);
badass.push(["Laure Conan","Something to Write About Home","Marie-Louise-F&eacute;licit&eacute; Angers, or, \"Laure Conan\" to her readers, was a French-Canadian author born in 1845. That's the same 1845 that had women tied up in corsets, cooking and baby-making. Mhmm. Girlfriend remained unmarried and wrote ELEVEN novels. Laure's style explored the minds of her characters within contemporary Quebec family structure, while the real-life lady told traditional Quebec family structure where they could shove it. #allthesingleladies ","img/default","https://en.wikipedia.org/wiki/Laure_Conan","dark"]);
badass.push(["Flora MacDonald Denison","Done Messing Around","Born in 1867, Flora MacDonald Denison was so tired of this stupid \"women aren't allowed to vote\" rubbish she started getting aaaall uppity. \"Whoa, Flora &mdash; calm it down, girl\" said Canada and Flora said, \"Here's what I think. Women should have the vote. Religion needs to chill out. Marriage needs to loosen-up. Birth control needs to be a thing, and let's not go to war.\" PREACH sister.","img/flora-macdonald-denison","http://www.thecanadianencyclopedia.ca/en/article/flora-macdonald-denison/",""]);
badass.push(["Carrie Derick","Genius Geneti-sister","What did years of tireless no-crap-taking and relentless research in genetics get Carrie Derick? Three points for guessing \"the honour of becoming Canada's first female university professor.\" Minus two points for forgetting that she was awarded a third the salary of her male counterparts. And this was after she did everything to earn her PhD (except have a penis).","img/default","https://en.wikipedia.org/wiki/Carrie_Derick","dark"]);
badass.push(["Viola Desmond","Viola Victorious","When she was told to leave the whites-only area of a Nova Scotia theatre in 1946, Viola Desmond told those racist jerks to shove it. (Basically she said that.) But the wildly unjust tax violation charge (for ONE CENT) brought against her when she refused to leave made her case famous, and helped launch the civil rights movement in Canada. For more Viola, keep your eyes on the $10 bill&hellip;","img/viola-desmond","https://en.wikipedia.org/wiki/Viola_Desmond",""]);
badass.push(["Pauline Donalda","Nice Work if You Can Get It","Montreal-born Pauline Donalda was 22 years old when her operatic debut in Nice, France dropped everyone's jaws. After performing all over Europe and America, she retired at 40 to devote her life to fostering new talent. With young singers on the rise and two husbands left in the dust, Pauline lived up to her motto: You must work, work, work! ","img/default","https://en.wikipedia.org/wiki/Pauline_Donalda","dark"]);
badass.push(["On&eacute;sime Dorval","Woodwork it, Grrrl","A literal trailblazer (no seriously) On&eacute;sime Dorval walked ahead of an oxcart caravan across the Prairies for two months in the 1880s to arrive in the bustling metropolis (read: tiny armpit settlement) of Duck Lake, Saskatchewan. Ignoring the fires, mosquitoes, dust, and bad food, On&eacute;sime became Saskatchewan's first teacher and a pioneer of bilingual education. Oh, and she could paint and woodwork like a boss because why not?","img/default","https://en.wikipedia.org/wiki/On%C3%A9sime_Dorval","dark"]);
badass.push(["Allie Vibert Douglas","Viberts are from Venus","Want both an asteroid and a crater on Venus named after you? Step 1: Get tossed out of the stupid boys-only science club in high school. Step 2: Become the first woman in North America to earn a PhD in astrophysics. Step 3: Savour a really awkward high-school-reunion conversation with your former (male) science teacher.","img/default","https://en.wikipedia.org/wiki/Vibert_Douglas","dark"]);
badass.push(["Mary Two-Axe Earley","Sexism Got the Chop","Some people, who may or may not be Mary Two-Axe Earley, receive National Achievement awards for their commitment to women's rights, specifically correcting gender discrimination within the Indian Act. Some people are also powerful clan mothers who devote their whole lives to organizing and campaigning for justice. They also hold a doctorate from York. Actually, yeah, that's all just Mary Two-Axe Earley. She's basically a one-of-a-kind.","img/default","https://en.wikipedia.org/wiki/Mary_Two-Axe_Earley","dark"]);
badass.push(["Sarah Emma Edmonds","Cash Me Outside&hellip; Like, Fighting in the Civil War","Not particularly interested in an arranged marriage, Sarah Emma Edmonds left her native New Brunswick for the United States at just 15. Told she couldn't serve her adopted country, Sarah \"I-Do-What-I-Want\" Edmonds rolled her eyes, and simply disguised herself as a man. Her book, Nurse and Spy in the Union Army, sold 175,000 copies.","img/default","https://en.wikipedia.org/wiki/Sarah_Emma_Edmonds","dark"]);
badass.push(["Henrietta Muir Edwards","Stop the Presses","With no Jezebel or Lenny Letter — not even a tattered back issue of Ms. Magazine — 19th-century feminists desperately needed something to read that didn't totally suck. So, Henrietta Muir Edwards and her sister trained an all-female staff to put out Woman's Work in Canada, the first Canadian 'zine for working women. Move over, Riot Grrrl. We got this.","img/henrietta-muir-edwards","https://en.wikipedia.org/wiki/Henrietta_Edwards",""]);
badass.push(["Leone Norwood Farrell","What is This? A Polio Vaccine for ANTS?","Dr. Salk and Co. developed the polio vaccine, which is nice and all, but couldn't figure out how to manufacture enough of it to treat real people. Step aside, boys club. After Leone Norwood Farrell stepped in and solved everybody's problems, do you think she got any credit for her, you know, life-saving ingenuity? Twenty years after her death society was finally like, \"Oh&hellip; um. Yeah that was our bad.\" #HERstory.","img/default","http://www.healthheritageresearch.com/Farrell/Farrell-TS20050417.html","dark"]);
badass.push(["Faith Fenton","The Ontarian Jekyll and Hyde ","Born 1857, Alice Freiman was a school teacher. After about five minutes of teaching arithmetic to those little snot-nosed monsters Alice realized she was unsatisfied, and the super sexist age didn't offer many other options. So, naturally, Alice took the pseudonym of Faith Fenton and secretly became an investigative journalist. Thereafter, \"Faith\" tackled contentious subjects like sexual discrimination, harassment, child abuse, and unfair pay, while \"Alice\" taught school.","img/faith-fenton","https://en.wikipedia.org/wiki/Faith_Fenton",""]);
badass.push(["Joan Bamford Fletcher","Welcome to the Jungle (I'mma Save You)","So. You're in Sumatra with 2,000 Dutch civilian prisoners at the end of WWII. What do you do!? Rally them up and walk to safety through a dangerous jungle full of Indonesian rebels, duh. Then the Queen gives you a fancy medal and you get all sorts of other accolades for doing this awesome thing. Also your name is Joan Bamford Fletcher (sorry, should have told you that part sooner...).","img/joan-bamford-fletcher","http://esask.uregina.ca/entry/bamford_fletcher_joan_1918-79.html",""]);
badass.push(["Lillian Bilsky Freiman","Make Poppies, Not War","Next time you accidentally poke yourself with a Remembrance Day poppy, you can thank philanthropist Lillian Freiman. No, she didn't begin the poppy campaign in Canada to annoy you (seriously, everything isn't about you...) she did it to help World War I veterans. Oh, and she saved a bunch of Jewish war orphans too. So get over your #firstworldproblems and bow down to the Poppy Lady.","img/default","https://en.wikipedia.org/wiki/Lillian_Bilsky_Freiman","dark"]);
badass.push(["Rose Fortune","Business Women, Policewoman, Super Woman","During the American Revolution, Rose Fortune got the heck out of slavery and moved to Nova Scotia where most black loyalists were struggling to make a living. However, lucky for Rose, she had never fallen into the category of \"most people.\" Boss lady built her own successful luggage transporting business, and began enforcing curfews and the wharves, which low-key makes her the first female police officer in Canada.","img/rose-fortune","https://en.wikipedia.org/wiki/Rose_Fortune",""]);
badass.push(["Dr. Ursula Franklin","Do All the Things","It might be easier to talk about what Ursula Franklin didn't do, instead of what she did. Can we do that? No? C'mon. Dr. Franklin was a world-renowned physicist, writer, peace activist, feminist and tireless advocate for human rights. She survived the Nazi atrocities, immigrated to Canada, and then she did a lot more stuff. Once expelled from university during the war, Ursula now has literally dozens of honourary degrees.","img/default","https://en.wikipedia.org/wiki/Ursula_Franklin","dark"]);
badass.push(["Marie G&eacute;rin-Lajoie","Sisters Doin' It for Themselves","Marie G&eacute;rin-Lajoie has some buildings and streets named after her. Probably because she lived a really boring life and never did anything important. Or, possibly, it's because she was an author, educator, social activist and suffragist BOSS. Marie was a self-taught legal expert (what, like it's hard?) and was fighting for the vote in Quebec before you were even born. How about a nice little thank you for Marie, huh?","img/marie-gerin-lajoie","https://en.wikipedia.org/wiki/Marie_Lacoste_G%C3%A9rin-Lajoie",""]);
badass.push(["Hilwie Hamdon","The First Mosque in Alberta","Born in Lebanon in 1917, Hilwie Hamdon emigrated to northern Alberta as a teenage bride. No sweat! After settling in Edmonton, Hilwie couldn't help but notice that the super-white, colonial town offered no central hub for the Muslim community. Her friends were like: \"We should build a hall\" and Hil' was all, \"How 'bout we build a mosque?\" So she DID. It was Canada's first mosque.","img/default","https://edwomencan.wordpress.com/2008/12/18/women-behind-al-rashid-mosque/","dark"]);
badass.push(["Hattie Rhue-Hatchet","She's Got the Beat","Hattie Rhue Hatchet, a child of escaped slaves, was born during the American civil war. Pretty much as soon as she could gurgle, little Hattie took to music, specifically piano. Against literally all odds &mdash; like &mdash; failure was so, so much more likely, Hattie became a revered music teacher, songwriter, and composer in what is now North Buxton, Ontario.","img/default","http://www.virtualmuseum.ca/edu/ViewLoitDa.do;jsessionid=3A18487C7BFDB29E6A26C89EC94DFEC0?method=preview&lang=EN&id=18664","dark"]);
badass.push(["Ann Harvey","The Grace Darling of Newfoundland","When she was 17 years old Ann Harvey helped save 163 people from a wrecked ship headed for Quebec City. One hundred. And sixty. Three. People. What you were doing when you were 17?! Oh, and one more tidbit about good ol' Ann: 10 years later, she saved another 25 people from a different shipwreck at the same spot. (Maybe stop sailing there? I don't know?) ","img/ann-harvey","https://en.wikipedia.org/wiki/Ann_Harvey",""]);
badass.push(["Anne H&eacute;bert","Triple Threat","Throughout her long and varied career as a poet, playwright and novelist, Anne H&eacute;bert earned a list of accolades that basically makes her the Beyonc&eacute; of French-Canadian literature. Plus, this single lady won the Governor General's Award three times. And she was appointed a Companion of the Order of Canada. Who run the world, indeed.","img/anne-hebert","https://en.wikipedia.org/wiki/Anne_H%C3%A9bert",""]);
badass.push(["Esther Hill","A Redesigned Glass Ceiling ","What would city skylines look like if trailblazing women architects like Esther Hill hadn't been shoved in the margins? (Hint: maybe there would be fewer buildings out there that look like giant penises.) Our girl Esther didn't get enough chances to build her dreams — you suck, misogyny — but she still broke barriers in the male-dominated, hugely overcompensating world of architecture. ","img/esther-hill","https://en.wikipedia.org/wiki/Esther_Hill",""]);
badass.push(["Lotta Hitschmanova","Ride into the Conflict Zone","Prague-born Lotta Hitschmanova achieved her PhD in journalism and French studies in order to freelance-write the heck out of some anti-Nazi sentiments. When Germany was all \"Hey, that's not cool,\" Dr. Lotta fled to Belgium, then France and finally Canada. Less than 100 pounds and with $60 in her pocket, Lotta quickly excelled, devoting the rest of her life to offering relief to war-torn Europe. ","img/default","https://en.wikipedia.org/wiki/Lotta_Hitschmanova","dark"]);
badass.push(["Helen Sawyer Hogg","Far Out, Man","\"Reach for the stars\" is just a saying, Helen. No, Helen, It's FIGURATIVE, HELEN. Well, whatever. Helen Sawyer-Hogg wasn't great with metaphors, so she pioneered research into globular clusters and variable stars. Then, she became president of several astronomical organizations when most universities were like \"Oh, yeah no. No you're a girl, so. Nope.\" Asteroid 2917 Sawyer Hogg is named after... well, you figure it out. ","img/helen-sawyer-hogg","https://en.wikipedia.org/wiki/Helen_Sawyer_Hogg",""]);
badass.push(["Adelaide Hunter Hoodless","Knowledge is Power","After the death of her infant son in 1889 from meningitis, possibly brought on by poor hygiene practices, Adelaide Hoodless had had enough. In a world where no one tells you anything when you have lady parts, Adelaide thought, \"This is ridiculous,\" and began what would become the Women's Institute, where women gather to educate each other about important issues relating to their lives. ","img/adelaide-hunter-hoodless","https://en.wikipedia.org/wiki/Adelaide_Hoodless","dark"]);
badass.push(["E. Pauline Johnson","The Best of Two Worlds","Too exotic to her white family, and too white for her aboriginal cousins, \"Tekahionwake\" (literally, \"double-life\") E. Pauline Johnson experienced some pretty nasty discrimination growing up mixed race. But this artist and writer wasn't about to throw in the proverbial, Victorian towel. Pauline celebrated her mixed heritage through poems and performance, becoming an anthologized Canadian icon.","img/e-pauline-johnson","https://en.wikipedia.org/wiki/E._Pauline_Johnson",""]);
badass.push(["Leonora King","Double Dragon Doctor","Rejected by Canadian medical schools for having lady parts, Leonora King took her lady brain to the U.S. and became a doctor anyway. A missionary doctor in China for 47 years, she was granted the Order of the Double Dragon and became a mandarin of the Chinese court. The honour brought her fame AND an ermine coat. #fashioninspo","img/leonora-king","https://en.wikipedia.org/wiki/Leonora_King",""]);
badass.push(["Tsukiye Muriel Kitagawa","Everything to Write Home About","Tsukiye Muriel Kitagawa was born in Vancouver (a second generation Japanese-Canadian) in 1912, and then unceremoniously forced into internment in 1942 because of her Japanese heritage. Tsukeye thought this was a pretty condemnable (YEP) and thought it deserved to be written about (YEP) so that's what she did. Her excellent essays highlight injustices to which Canada must be held accountable.","img/tsukiye-muriel-kitagawa","https://remarkablewomen2014.wordpress.com/2013/09/26/muriel/",""]);
badass.push(["Elsie Knott","Who run the world? Go on. Guess.","Elsie Knott was the first of her kind. After the Indian Act was amended to give First Nations women the right to run for band leadership, Elsie became the first woman elected as chief of a First Nation. Oh, and then she won seven. More. Times. Her legacy? Working to preserve the Ojibwe language and supporting her community like a boss. (Like an actual boss.)","img/default","https://en.wikipedia.org/wiki/Elsie_Knott","dark"]);
badass.push(["Molly Kool","More Like: Molly so Freakin' Kool, Amiright?","Molly, Molly, Molly. Don't you know women aren't supposed to be sea captains? Wait, you don't? Oh, okay then. After lady-boss earned her official captain's stripes in 1939 Nova Scotia, a line in the Canadian Shipping Act had to be changed to include the word \"she.\" Heck yeah, Molly. And way to go on the whole being a ship-master thing, too.","img/default","https://en.wikipedia.org/wiki/Molly_Kool","dark"]);
badass.push(["Marguerite Vincent Lawinonki&eacute;","These Shoes are Made for Culture-Rescuing ","Marguerite Vincent Lawinoki&eacute; took moose-hair and porcupine quills and turned them into on fleek works of orthopedic ART. (Shoes. She made super cool shoes.) Her creations literally helped save her village and have preserved Huron-Wendat culture for generations. Marguerite's community decided to make this whole shoe business thing their official jam, and now over 60 families produce over 30,000 moccasins every year. All. By. Hand. ","img/default","https://en.wikipedia.org/wiki/Marguerite_Vincent_Lawinonki%C3%A9","dark"]);
badass.push(["Florence Lawrence","Eat Your Heart Out, Hollywood","Considered the \"The First Movie Star,\" Florence Lawrence appeared in over 300 films. Three-hundred. That's&hellip; that's a lot of freakin' films. Oh, and also owned a successful store. And was an automotive inventor. And had her own line of cosmetics. Probably she had lots of time for these things because she wasn't in that many fil&hellip; oh, wait.","img/default","https://en.wikipedia.org/wiki/Florence_Lawrence","dark"]);
badass.push(["Irma LeVasseur","Dr. LeVasseur. You Heard Right. ","In 1900, when Quebec told Irma LeVasseur that women can't be doctors, Irma said: \"That's nice. I'm going to become a doctor tho, so&hellip;\" After practising medicine in New York City, her relentless determination resulted in the passing of a private bill in the Quebec Assembly allowing her to practice at home. The first female Quebec physician, she also helped establish several hospitals. We think that's, you know, pretty cool. ","img/default","https://en.wikipedia.org/wiki/Irma_LeVasseur","dark"]);
badass.push(["Jean B. Lumb","Yep, That's \"B\" for \"Boss\"","When Jean B. Lumb noticed that Chinese families were suffering separation due to laughably racist immigration laws, she sat down on the chesterfield and said, \"Oh well, that's life.\" JK!!! Jean got that baloney straightened out and went on to save a couple Chinatowns in the process. Oh, and she owned a grocery store and raised six kids at the same time NBD. ","img/default","https://en.wikipedia.org/wiki/Jean_B._Lumb","dark"]);
badass.push(["Elsie MacGill","Queen of Hurricanes","The first female airplane designer and the world's first woman to earn an aeronautical engineering degree, Elsie MacGill wore the pants. (Which was super scandalous at the time, oh my.) Elsie contracted polio and was told she'd never walk again, but girlfriend didn't have time for that noise. She engineered herself some canes so she could continue her day-to-day of being an absolute boss. ","img/elsie-macgill","https://en.wikipedia.org/wiki/Elsie_MacGill",""]);
badass.push(["Helen Gregory MacGill","In Tune and Out of Sync","You know when you're up to your eyeballs in being the first female judge in British Columbia and the only one in Canada, and also writing as a journalist on the side for Cosmopolitan, and also, you know, fighting for women's rights every day, you think: \"I should be the first woman in the entire British Empire to earn a music degree?\" No? Just Helen Gregory MacGill? K.","img/helen-gregory-macgill","https://en.wikipedia.org/wiki/Helen_Gregory_MacGill",""]);
badass.push(["Viola R. MacMillan","The OG Gold Digger","Scanning the rocky terrain of the Canadian Shield, Viola MacMillan knew there was gold in them thar hills, and she wasn't afraid to go get hers. Not above using her husband's name to file her mining claims as women weren't legally allowed to get their hands dirty, Viola found major gold deposits across Canada — YASSSS — and was the first female inductee to the Canadian Mining Hall of Fame.","img/default","https://en.wikipedia.org/wiki/Viola_R._MacMillan","dark"]);
badass.push(["Helen MacMurchy","Public Health Champion","Do you think that Helen MacMurchy gave a shi... nbone that in the 1890s, women didn't typically work in medicine? Hmm? Do ya? After gaining valuable firsthand experience with childbirth, Helen wrote a book for mothers (wait, women can read?) that mixed medical research with common language, which was all sorts of practical. Way to save them babies, Helen.","img/default","https://en.wikipedia.org/wiki/Helen_MacMurchy","dark"]);
badass.push(["Agnes Campbell Macphail","Lady-Like Legislating","Agnes Campbell Macphail knew a thing or two about&hellip; well, kind of everything. The first woman to be elected to parliament, she worked for two separate Canadian parties and was a strong voice for rural issues and penal reform. Agnes said it best: \"Most women think politics aren't lady-like. Well, I'm no lady. I'm a human being.\" #AGNES. ","img/agnes-campbell-macphail","https://en.wikipedia.org/wiki/Agnes_Macphail",""]);
badass.push(["Clara Brett Martin","Clara Martin, Juris Doctor","Clara Brett Martin was a smart little girl who (got her B.A. in mathematics at 16) did lots of nice things (petitioned the Law Society of Upper Canada to let her in despite her gender) had nice hobbies (paved the way for female lawyers in Canada) and read lots of nice books (understood the importance of education to the future for Canadian women). You know, nice stuff like that.","img/clara-brett-martin","https://en.wikipedia.org/wiki/Clara_Brett_Martin",""]);
badass.push(["Nellie McClung","Let Them Howl","One time, someone told Nellie McClung she couldn't vote. \"Um, yeah I don't like that. We should probably change that,\" she said. So&hellip; she did. After a whole life dedicated to women's rights, including notable victories like getting women \"person\" status under the law, Nellie says it best: \"Never explain, never retract, never apologize. Just get the thing done and let them howl.\" Heck. Yes. Nellie. #howlyourheartout","img/nellie-mcclung","https://en.wikipedia.org/wiki/Nellie_McClung",""]);
badass.push(["Frances Gertrude McGill","Sherlock Holmes of Saskatchewan","To make one Frances Gertrude McGill: gather all characters from CSI, and blend. Remove all clich&eacute; catch lines and sunglasses. Remove modern conveniences. Add incredible perseverance to master fields previously reserved for men. Add medals for highest student average. Add bacteriologist experience. Add pathologist experience. Finally, add this personally coined motto: \"Think like a man, act like a lady and work like a dog.\" Mix well, serve immediately.","img/default","https://en.wikipedia.org/wiki/Frances_Gertrude_McGill","dark"]);
badass.push(["Louise McKinney","Feminist Elect","There are reasons the Famous Five are, well, famous. Louise McKinney persevered through moronic sexism at best, physical threats at worst, to become the first woman sworn into the Legislative Assembly of Alberta (hence also the first woman elected to a legislature in Canada and the British Empire). Tough as nails and resiliant af, McKinney favoured \"radical\" ideas like female education and women's property rights. ","img/louise-mckinney","https://en.wikipedia.org/wiki/Louise_McKinney",""]);
badass.push(["Maud Menten","\"Petite Dynamo\" aka Dr. Boss","When Canada told physician-scientist Maud Menten she wasn't allowed to do research here because of her bad luck in the genetic lottery, she was like \"Whatever dudes. I'll take my genius elsewhere.\" Turns out Germany was very happy to have her, awarding her a PhD in 1916. Besides enormously advancing her field, Maud's personal interests were freaking awesome: mountain climbing, painting, language-learning, astronomy, girl. Way to go.","img/default","https://en.wikipedia.org/wiki/Maud_Menten","dark"]);
badass.push(["Mikak","I'm Not Exotic YOU ARE","Mikak was an Inuk woman from 1740 Labrador who didn't give a canoe that most of her people were afraid of the Europeans. Smart, industrious and brave-af, Mikak was the first Inuit woman to travel to Europe, return back to Canada and share stories that went something like: \"They're all as white and fragile as snow, you guys. They're basically screwed.\"","img/mikak","https://en.wikipedia.org/wiki/Mikak","dark"]);
badass.push(["Dorothea Mitchell","Lady Lumberjack","Dorothea Mitchell did the following things on her own, while unmarried: gained a homestead in Ontario. (Gasp!) Purchased a sawmill and hired workers. (What!?) Took a filthy cheat to court and won. (For real?) Excelled at photography and writing. (Ok stopit.) Made several films. (Well this is just OUTRAGEOUS.) Oh, and kicked butt at absolutely ALL of it. So, what have you been up to lately?","img/default","https://en.wikipedia.org/wiki/Dorothea_Mitchell","dark"]);
badass.push(["Ga'axstal'as","A Controversial Matriarch","Raising 16 kids and working as a midwife wasn't enough for Kwa'waka'wakw noble woman Ga'axstal'as Jane Constance Cook. Nope. She had some time to kill, so she developed insane communication skills by perfecting her bilingualism, studied the colonial legal systems and actively sought legal reform on local, provincial and even federal levels. For women's rights especially, Ga'axstal'as was a ga'axs-kicker.","img/default","http://bcbooklook.com/2014/01/11/jane-cook-crusading-matriarch/","dark"]);
badass.push(["Marcelle Ferron","Bold Work from a Bold Woman","One day Marcelle Ferron picked up some glass and said: \"I'm gonna make art just like everyone else's and it'll be really boring and no one will like it.\" Hahaha&hellip; no she didn't! This art school drop-out did her own thaaaang making incredible, vibrant pieces unlike anything that came before. From the metro in Montreal to the Quebec court house, sister brought colour and life to the Canadian arts. ","img/default","https://en.wikipedia.org/wiki/Marcelle_Ferron","dark"]);
badass.push(["Margaret Laurence","Banned and Required Reading","Margaret Laurence travelled the world, living in England and Africa, only to come back to the same tiny boring Manitoba town and, somehow, make us care about it. Neepawa (or, \"Manawaka\" in her work) is not an inconsequential backdrop for her most widely read fiction, works that force us to confront difficult truths and empathize with difficult characters. Though previously banned for sexual content (oh, phooey), Margaret's voice will not be silenced.","img/default","https://en.wikipedia.org/wiki/Margaret_Laurence","dark"]);
badass.push(["Julia Verlyn LaMarsh","Thank Goodness Someone's Looking After Things","Julia Verlyn LaMarsh was a federal cabinet minister, and secretary of state for Canada. Which, is like, pretty cool or whatever. In the 60s, when everyone was busy getting high with flowers on their heads, she was like: \"You know what we should support? LGBTQ rights.\" And, \"You know what we shouldn't support? Tobacco smoking. It's gross.\" And, \"Also, we need Medicare.\" So many good ideas. #cabinetministerwin","img/default","https://en.wikipedia.org/wiki/Judy_LaMarsh","dark"]);
badass.push(["Justice Bertha Wilson","She is the Law (and She Won)","Fair, firm, and crazy awesome, little Bertha Wilson settled playground marble disputes like a friggen boss. Oh, and then emigrated to Ontario and became was the first woman appointed to the Supreme Court of Canada or whatever. Actually, wait, that's kinda important; Bertha helped bang out legislation for some super imperative issues for women, like reproductive rights and battered wife syndrome. Dang, Bertha. #ThanksGirl","img/default","https://en.wikipedia.org/wiki/Bertha_Wilson","dark"]);
badass.push(["Helen Irene Battle","Blinding Us with Science","A woman walks into a marine biology lab... It was Dr. Helen Battle, the pioneer zoologist. Oh you were expecting a joke there? You monster. Through years of zero-crap-taking and academic trailblazing — first Canadian woman to earn a PhD in marine biology, thank you very much — plus her groundbreaking research methods, she quietly paved the way for female scientists from coast to coast to coast.","img/default","https://en.wikipedia.org/wiki/Helen_Battle","dark"]);
badass.push(["Sylvia Fedoruk","Multifaceted Bossery","So, a medical hall of fame member, a curling champion and the Lieutenant-Governor of Saskatchewan walk into a bar&hellip; and she sits down. Yeah. Like, holy crap, Sylvia, way to make the rest of us feel like big ol' failures. Oh wait, you're not done? You were also awarded the Order of Canada? Of course you were, Sylvia. Of course you were. ","img/default","https://en.wikipedia.org/wiki/Sylvia_Fedoruk","dark"]);
badass.push(["Cathleen Synge Morawetz","Riding the High Frequency Wave","Cathleen Synge Morawetz pioneered advances in partial differential equations and wave propagation math. (Don't Google that and pretend you know what it means. No one does. Except for Cathleen.) She put those concepts to work in aerodynamic, acoustic and optic fields, improving everyone's lives. She was told her family would suffer if she went to work, which is probably why she has four successful children and six grandchildren.","img/default","https://en.wikipedia.org/wiki/Cathleen_Synge_Morawetz","dark"]);
badass.push(["Vera Peters","Just What the Vera Peters Ordered","If you, or someone you know has survived breast cancer, you might want to include Vera Peters' name in your expressions of thanks. Not only did Dr. Awesome, I mean, Vera demonstrate that specialized surgery followed by radiation was just as effective as mastectomy, she actually CURED patients with early Hodgkin's disease, a condition previously thought to be fatal. #literallifesaver #notthecandy","img/default","https://en.wikipedia.org/wiki/Vera_Peters","dark"]);
badass.push(["Kim Thúy","Au Revoir Vietnam, Bonjour Quebec","How many overcrowded Malaysian refugee camps did you hang out in before arriving to Canada on an old-school boat from communist Vietnam, learning English and French on the fly and figuring out what in the heck is going on? Oh, none? Well Kim Thúy did that. At 10 years old. And y'know what else? She's also NICE, and a freaking TALENTED-AF, internationally acclaimed author. Just stoppit, Kim Thúy. ","img/kim-thuy","https://en.wikipedia.org/wiki/Kim_Th%C3%BAy",""]);
badass.push(["C&eacute;line Galipeau","Coming to You from Literally Everywhere","Currently a news anchor for Radio Canada, Celine Galipeau has awesome-d her way around the globe speaking truths, winning awards, and basically just improving everyone's lives. Maybe that's why she was named to the Order of Canada. (Or she just asked them really nicely. I wonder if that works?) Anyways, they don't give out Gemini Awards for nuthin. Celine got hers for her foreign correspondent-ing like a boss from Moscow.","img/celine-galipeau","https://en.wikipedia.org/wiki/C%C3%A9line_Galipeau",""]);
badass.push(["Irene Uchida","Ms. Medical Mastermind","When Irene Uchida heard that people with Down's Syndrome have 47 chromosomes instead of the normal 46, she was like, \"Whoa whoa whoa WHOA.\" Then she went ahead and created Canada's first clinical cytogenetics program, discovered all sorts of other important shiz, and published over 95 scientific papers on medical science. Which, incidentally, is 95 more scientific papers than you've published. ","img/default","https://en.wikipedia.org/wiki/Irene_Uchida","dark"]);
badass.push(["Anna Ruth Lang","Into the Fire","There's brave, like \"I-squished-a-huge-spider\" brave, and then there's nuts insanity \"Anna Ruth Lang\" brave, whose car was hit by a fuel tanker truck, both falling into a river. Suffering a concussion, Anna nevertheless rescued two other passengers WHILE SWIMMING THROUGH FIERY WATERS. No wonder she was awarded the Cross of Valour, only given to Canada's most brave. Bet she also takes care of those spiders.","img/default","https://en.wikipedia.org/wiki/Anna_Ruth_Lang","dark"]);
badass.push(["Jeanne Mance","Co-Founder of Montreal","Jeanne Mance co-founded the city of Montreal, literally laying foundations and setting up its first hospital. But is she a well-celebrated pioneer settler? No. Why? I'll give you a hint: it rhymes with \"shmexism.\" ANYWAYS, nurse turned nun turned tough-as-nails settler, Jeanne single-handedly saved the colony more than once, raised funds for public health and defense and was a life-long caregiver. #CanadianHERstory","img/jeanne-mance","https://en.wikipedia.org/wiki/Jeanne_Mance",""]);
badass.push(["Jennie Trout","That's Dr. Trout to You","If you were suffering an illness, would you go to a doctor? Or just straight up BECOME one? In 1871, Jennie Trout became the first Canadian woman to achieve a medical license. The incredible hostility she faced from both peers and professors is enough to make you want to meat-grind your girdle, but Jennie showed those idiots. Ten years later, she helped open the Women's Medical College at Kingston.","img/default","https://en.wikipedia.org/wiki/Jennie_Kidd_Trout","dark"]);
badass.push(["Lucy Maud Montgomery","Girl from the Island","You: a prolific author of homespun tales set on Prince Edward Island. Us: a young nation in need of some cultural identity in the form of a delightfully plucky red-headed heroine. We smiled at each other near that house with the green gables. Haven't been able to get you off our minds since. Meet for a raspberry cordial?","img/lucy-maud-montgomery","https://en.wikipedia.org/wiki/Lucy_Maud_Montgomery",""]);
badass.push(["Geraldine Moodie","H8ters Will Say It's Photoshopped","Geraldine Moodie didn't have Instagram in the late 1800s, but she totally would have had bajillions of followers and used hashtags like #nofilter and #outdoorinspo. Needless to say, Geraldine knew how to capture a freakin' moment, and her pix made it all the way back to the prime minister who started following her and liking all her stuff from ages ago like a creep.","img/geraldine-moodie","https://en.wikipedia.org/wiki/Geraldine_Moodie",""]);
badass.push(["Sophie Morigeau","Frontier Woman","Married off at age 16, Sophie Morigeau could've become a Real Housewife of the M&eacute;tis. Instead she was like, \"yeah no,\" peaced out and started a successful trading post for BC gold miners. That said, she didn't make it through completely unscathed — a lost eye, a self-amputated rib, a string of loser lovers (some of whom she may have shot or drowned) — she did it all on her own terms. ","img/sophie-morigeau","http://www.thefreepress.ca/news/223047531.html",""]);
badass.push(["Phyllis Munday","Ain't No Mountain High Enough","An early mountaineer with clearly no healthy sense of fear, Phyllis Munday almost died saving her husband from falling to his death in a crevasse, and later took her 11-week-old daughter to the summit of a mountain. Phyllis was the first person to reach the summit of like nine different mountains, lived in a tent for three years and founded the Girl Guides of British Columbia. #PHYLLIS.","img/default","https://en.wikipedia.org/wiki/Phyllis_Munday","dark"]);
badass.push(["Emily Murphy","She'll Be the Judge of That","Told she couldn't attend a prostitution trial because the testimony was \"unfit\" for women's delicate sensibilities, Emily Murphy, (whose sensibilities were many things but none of them \"delicate\"), was like: \"We should probably create a women-only court then.\" The Alberta government was like \"Actually, yeah. Here you go,\" and put her in charge. Judge Murphy became the first woman magistrate in the British Empire. (With not a single faint.)","img/emily-murphy","https://en.wikipedia.org/wiki/Emily_Murphy","dark"]);
badass.push(["Nahnebahwequa","This Land is My Land, For Real Tho","Nahnebahwequa earned her place in history when she went up to Queen Victoria all: \"You should probably let us own our land. Since it's already our land.\" And Vicky was all: \"Okay, but just for you 'cause racism is still kind of on-brand for us.\" In Ojibwe, Nahnebahwequa means \"upright woman,\" but a more modern translation would just be \"boss.\"","img/default","https://en.wikipedia.org/wiki/Nahnebahwequa","dark"]);
badass.push(["Irene Parlby","A Person's a Person No Matter How Female","Irene Parlby believed the word \"person\" should apply to um, well... persons. Even those who don't own land, or weren't born with boy-parts. The Canadian government wasn't sure though, so Irene and four of her closest person-friends appealed all the way to the British courts to get that hogwash sorted out. Then she became the first female cabinet minister in Alberta, and personed all day err'day like a boss. #girlsarepersonstoo","img/irene-parlby","https://en.wikipedia.org/wiki/Irene_Parlby",""]);
badass.push(["Madeleine Parent","A Protest Powerhouse","When faced with the discrimination of others, do you sympathize? Do you give them a hug? Do you willfully go off to jail so that they can continue protesting and eventually achieve union status under the law? Hmm. I guess you just don't care. But Madeleine Parent did, about so many causes it's downright dizzying. Her heroic activism has changed the lives of countless Canadians, making her a Quebec icon.","img/madeleine-parent","https://en.wikipedia.org/wiki/Madeleine_Parent",""]);
badass.push(["Mona Louise Parsons","The World Needs More Monas","Mona Louise Parsons risked death and worse to shelter Allied airman in her home during WWII. (What's worse, you ask? You don't want to know.) When Mona was captured and sentenced to die, her incredibly calm demeanour surprised the judge so much, he allowed an appeal. The only Canadian female to be imprisoned by the Nazis, Mona would later be personally commended by Dwight Eisenhower for her bravery.","img/mona-louise-parsons","https://en.wikipedia.org/wiki/Mona_Louise_Parsons","dark"]);
badass.push(["Georgina Pope","Somebody Give that Lady a Medal","High-born Georgina Pope of P.E.I. could have married a nice dude and had lots and lots of servants to bring her cucumber sandwiches. Instead, she decided \"Nope, I'ma go be a nurse in an uncomfortable climate where there's too many sick people and not enough food. Mhmm, yep that sounds good.\" For her relentless efforts in South Africa, she was the first woman awarded the Royal Red Cross in 1903. ","img/georgina-pope","https://en.wikipedia.org/wiki/Georgina_Pope",""]);
badass.push(["Nellie Yip Quong","No-Nonsense Nellie","Nellie Yip Quong spoke five Chinese dialects and advocated for Chinese rights in Vancouver&hellip; and she wasn't Chinese. In 1900 Nellie \"Towers\" was disowned by her family after scandalously marrying Charlie Yip Quong. Nellie felt that the Canadian government's withholding of services to the Chinese community was racist (yep), so girlfriend just did it all herself. Translator, broker, midwife and law challenger &mdash; Nellie knew what was up.","img/default","https://en.wikipedia.org/wiki/Nellie_Yip_Quong","dark"]);
badass.push(["Fabienne Larouche","Queen of the Small Screen","INT. OFFICE &mdash; NIGHT. FABIENNE LAROUCHE sits at a desk, writing a screenplay that will once again prove her dominance as a Quebec's most prolific screenwriter and television producer. ENTER MISOGYNY: Stop wasting public funds and being so awesome. FABIENNE: Whatever. I'll just start my own production company and do my thang. FABIENNE IS MADE A KNIGHT OF THE ORDER NATIONAL DU QUEBEC. FIN.","img/fabienne-larouche","https://fr.wikipedia.org/wiki/Fabienne_Larouche",""]);
badass.push(["Kate Rice","I Am Sayin' She's a Gold Digger","Some people are so many awesome things it's downright annoying. Kathleen Creighton Starr Rice (<-- name goals) was a mathematics professor, a mountaineer, a \"new frontier\" homesteader, and a successful prospector. She taught herself geology, hunting, trapping and the Cree language all on her own. (Pfffft, easy.) For some reason, this blonde, six-foot-tall prospecting wonder was always being followed by the pesky press...","img/kate-rice","https://en.wikipedia.org/wiki/Kate_Rice",""]);
badass.push(["L&eacute;a Roback","A Relentless Reformer","L&eacute;a Roback thought that injustices like racism and violence were like, you know, bad. After realising that the morons around her didn't share her totally justifiable outrage, she vowed to devote her life to social activism. L&eacute;a fought for access to free and safe abortion, better housing, education and a million other things, so that today we can sit here watching cat videos and not getting dumped on by prejudice. ","img/lea-roback","https://en.wikipedia.org/wiki/L%C3%A9a_Roback",""]);
badass.push(["Marie Marguerite Rose","A Free Agent","Marie Marguerite Rose was a Guinea-born woman sold into slavery for 19 years, and emancipated in 1755. (Tell me again how hard your day was?) Once free, Marie married an emancipated Mi'kmaw man, and despite horrendous racism and sexism, opened a tavern near the barracks of Louisbourg, Nova Scotia. A dark-skinned, interracial couple mingling with other business owners and demanding the same rights? Um, yes. Yes that exactly. ","img/default","https://en.wikipedia.org/wiki/Marie_Marguerite_Rose","dark"]);
badass.push(["Gabrielle Roy","Take a Hard Look in the Mirror","Remember that time when, while earning your living doing something totally different, you wrote a novel on the side that inspired Quebec's Quiet Revolution of the 1960s? No? Oh, my bad. I'm confusing you with critically acclaimed Francophone author Gabrielle Roy. You know, one of the most significant writers of psychological realism in the history of Canadian literature? Sorry, you probably get that all the time. ","img/gabrielle-roy","https://en.wikipedia.org/wiki/Gabrielle_Roy",""]);
badass.push(["Idola St-Jean","Extend the Franchise. Period.","In 1927 Idola St-Jean and her lady squad went to visit Quebec Premier Louis-Alexandre Taschereau all: \"Here's what's going to happen here. You're going to extend the vote to women, we're going to enjoy equal representation, and I don't wanna hear no lip. Cool? \"Taschereau was like: \"Hmmmmm... nah.\" So, professor, journalist and suffrage pioneer Idola came back every year until 1940, when the next premier said \"Ok. Cool.\"","img/idola-st-jean","https://en.wikipedia.org/wiki/Idola_Saint-Jean",""]);
badass.push(["Catherine Schubert","I'm Coming with You, End of Discussion.","In 1862, when her husband decided to follow the gold prospectors to British Columbia, Catherine Schubert was like, \"Ohhhhh heck no. You think you're leaving me here with three little kids?\" So, four-months-pregnant Catherine packed up her children (5, 3 and 1), and travelled west through fricken freezing, treacherous surroundings. Lady went into labour on a RAFT and became the first woman ever to enter BC by land.","img/default","http://www.cbc.ca/archives/entry/catherine-schubert-crosses-the-rockies-in-1862","dark"]);
badass.push(["Laura Secord","This Petticoat was Made for Walkin'","Laura Secord didn't bust out the pedometer when it was time to walk 32 kilometers through the middle of the War of freakin' 1812. She just hiked up her skirt, kicked rocks through the Canadian wilderness and told the British: \"Just for your FYI, the Americans are coming and also I'm a war hero now. Kthxbye.\"","img/laura-secord","https://en.wikipedia.org/wiki/Laura_Secord",""]);
badass.push(["Lise Payette"," L'Article Feminin","Sticks and stones may break bones, but words can change a culture. That's why Lise Payette &mdash; longtime broadcaster, writer, politician and activist &mdash; pushed for the feminization of job titles in Qu&eacute;bec, including changing her own cabinet minister title, \"le ministre,\" to the grammatically incorrect \"la.\" Because \"la\" is for the ladies. And because screw grammar, amiright? ","img/default","https://en.wikipedia.org/wiki/Lise_Payette","dark"]);
badass.push(["Mary Ann Shadd","First Female Publisher in Canada","Mary Ann Shadd was a black, female newspaper editor in 1850, and holy crap, I can't believe I just wrote that. Like!? Ok sorry, focusing, focusing: Mary used her paper, the Provincial Freeman, to uplift and unite African-Americans and Canadians, enforce the importance of education and empower her community to fight back against racist perceptions. With zero formal training and no journalism experience, I just. Wow.","img/default","https://en.wikipedia.org/wiki/Mary_Ann_Shadd","dark"]);
badass.push(["Norma Shearer","A Liberated Act to Follow","Historians call actress Norma Shearer an, \"exemplar of sophisticated 1930s womanhood, &hellip; exploring love and sex with honesty.\" Problem is, her contemporaries weren't exactly ready to see her as an example of anything except \"acting like a tramp.\" Norma didn't give a rodent's behind that some people's delicate sensibilities were offended by her on screen, and real life behavior, and today she's considered a feminist pioneer.","img/norma-shearer","https://en.wikipedia.org/wiki/Norma_Shearer",""]);
badass.push(["Hide Hyodo Shimizu","Schooled Xenophobia","Why does Hide Hyodo Shimizu have the Order of Canada and you don't? Because she went to Ottawa to go: \"Give me the vote you dusty old racists\"? Because she was the first Japanese-Canadian to get a teaching certificate in BC? Or because she taught in Japanese internment camps before being interned herself? No. Because ALL those things. ","img/default","http://www.torontonajc.ca/2014/02/16/hide-shimizu-memorial-scholarship/","dark"]);
badass.push(["Angela Sidney","A Story Well Told","A much-loved Tagish Elder of the Delsheetaan nation, Angela Sidney told stories like a boss. No, not like YOUR boss, who bores you with detailed rundowns of his last golf game, but like a TRUE boss of indigenous storytelling who helped pass her people's culture on to the next generation. (No golf stories.) She even became the first native woman from the Yukon received the Order of Canada, making HERstory.","img/angela-sidney","https://en.wikipedia.org/wiki/Angela_Sidney",""]);
badass.push(["Elizabeth Lawrie Smellie ","Matron-in-Chief","\"Ew, blood!\" said Dr. Elizabeth Smellie never. After patching up the WWII wounded, Elizabeth hit up McGill University to teach another generation of nurses how to kick butt. You know&hellip; medically speaking. After that, in competition only with herself, Lizzy served as the first female colonel in the Canadian army as the medical corps' matron-in-chief in WWII. Yeah, \"matron-in-chief.\" AKA: Lady. Boss.","img/elizabeth-smellie","https://en.wikipedia.org/wiki/Elizabeth_Lawrie_Smellie",""]);
badass.push(["Ethel Stark","Female Soloist #sorrynotsorry","Not that long ago, women were virtually banned from orchestras. Because, you know, our lady hands and lady lungs just&hellip; can't, it's&hellip; so, hard, (It's all the same.) Ethel Stark saw this nonsense for what it was and became not only a boss violinist but the first woman to conduct an orchestra at Carnegie Hall, and the first female artistic director of a Canadian symphony orchestra. BAM.","img/ethel-stark","https://en.wikipedia.org/wiki/Ethel_Stark",""]);
badass.push(["Emily Stowe","No Time for Small Minds","In 1865, the vice-president of the Toronto School of Medicine refused Emily Stowe admission, with this little nugget of wisdom: \"The doors of the University are not open to women, and I trust they never will be.\" Sounds like a great guy, eh? So Emily Stowe went \"nope nope nope\" and went to study medicine in the States, before returning to TO and opening her own in-yo-face practice.","img/emily-stowe","https://en.wikipedia.org/wiki/Emily_Stowe",""]);
badass.push(["Chantal Peticlerc","Give Her the Gold and Shut Up","Chantal Petitclerc wins at everything. Probably including things you can't even win at, like meditation. This senator from Quebec (nbd&hellip;) has won more medals than any other women in the Paralympic Games, 1992&mdash;2008. Oh yeah, competitive boss lady lost the use of her legs as a child, but do you think that slowed her down? Chantal, I'm a little afraid of you, but also impressed af.","img/chantal-petitclerc","https://en.wikipedia.org/wiki/Chantal_Petitclerc",""]);
badass.push(["Thanadelthur","Not Lost in Translation","Chipewyan Thanadelthur, born 1697, was captured by Cree in 1713. Unimpressed, clever Thanadelthur escaped, only to be found by the Hudson's Bay Company. Annoyed by her terrible luck but hoping to get back to her people, she agreed to negotiate a peace agreement between Chipewyan and Cree. Sister negotiated and translated like a boss, BAM! Agreement. Ask me if she received payment for her work. Go ahead. Ask me. ","img/thanadelthur","https://en.wikipedia.org/wiki/Thanadelthur",""]);
badass.push(["Maud Watt","Angel of Hudson Bay","When the over-hunting of beaver threatened to collapse both the northern Quebec European and Cree economies, James Watt asked his wife, Maud, if she could help. By \"help\" he meant: \"K, I just need you to cross the frozen bay by dog sled with our two small children in -45, train to Quebec City and convince them to set land aside for a preserve.\" Maud was like, \"FFS, James. Yes.\" ","img/default","http://www.hbcheritage.ca/hbcheritage/history/people/women/maudwatt","dark"]);
badass.push(["Simonne Chartrand","Leader of Women and Men","Some people have a calling. Some people have alllll the callings. Simonne Chartrand actively supported feminism and human rights, as well as labour and union rights, all with a pacifist approach. Celebrated author, media personality and mother of seven, Simonne doesn't care that her numerous achievements make me feel like a failure, but she does care about basically everything else, making her a champion of modern activism in French Canada. ","img/simonne-chartrand","https://en.wikipedia.org/wiki/Simonne_Monet-Chartrand",""]);
badass.push(["Madelaine Redfern","Receive, Give back, Rock On","Madeleine Redfern said it right: \"Community empowerment rocks!\" YEAH it does! And you know what else rocks? You, Madeleine. As the current Mayor of Iqaluit and the first Inuk (male or female) to clerk at the Supreme court, you equip your community to become better, while challenging the historical chronicling of the Eastern Arctic Inuit as executive director of the Qikiqtani Truth Commission. ","img/default","https://en.wikipedia.org/wiki/Madeleine_Redfern","dark"]);
badass.push(["Janette Bertrand","Woman of the Century","Sometimes, women become writers. Other times, women become writer/actor/educator/radio-host&hellip; ers. And also they're born in 1925 Quebec. And their name is Janette Bertrand, and they're amazing. On a related note: Janette Bertrand, who is amazing, received the Prix Condorcet, an award given each year to a public figure who has contributed to freedom of conscience in Quebec. What a coincidence.","img/janette-bertrand","https://en.wikipedia.org/wiki/Janette_Bertrand",""]);
badass.push(["Dr. Alis Kennedy","An Outstanding Ontarian","Activist, M&eacute;tis leader and founding member of the Centennial College Aboriginal Studies Council, we're pretty sure Senator Dr. Alis Kennedy never sleeps. The first Indigenous woman to get a commercial pilot's license, Alis continues to work for so many causes it's baffling. There's an Alis for the Pan Am Games, an Alis for girls' education, an Alis for protecting big endangered cats (for real), and like, 1,000 other Alises. ","img/default","http://www.metisnation.org/news-media/news/m%C3%A9tis-senator-receives-ontario-medal-for-good-citizenship/","dark"]);
badass.push(["Tanya Tagaq","An Inuk Inspiration","Think you can do what Tanya Tagaq can? Depends: are you an Inuk Canadian who pioneered her own form of solo throat singing, a style usually only achievable with two singers? Good for you! Now all you've got to add is being a killer solo act who's also collaborated with international artists like Björk and earn the Order of Canada Member in 2016. Still there? Hello?","img/tanya-tagaq","https://en.wikipedia.org/wiki/Tanya_Tagaq","dark"]);
badass.push(["Buffy Saint&eacute;-Marie","The Blacklist Slayer","Buffy Saint&eacute;-Marie has a doctorate in getting in everyone's comfortable faces. (Actually, it's in fine arts, but she's still Dr. Saint&eacute;-Marie). They tried blacklisting her on the radio, so she went: \"How about I just rock being an iconic folk singer and native activist for four decades?\" Plus she co-wrote \"Up Where We Belong,\" which I'M NOT CRYING YOU ARE","img/buffy-sainte-marie","https://en.wikipedia.org/wiki/Buffy_Sainte-Marie","dark"]);
badass.push(["Lily Singh","Subscribe to #Superwoman","If you are under 18 (or totally hip with the kids), you'll be acquainted with one Lily Singh, the third-highest paid YouTube star on planet Earth. Lily's fans come for the hilarious skits, and stay for the celebratory #GirlLove. SuperLily is all about banishing girl-on-girl hate while revamping the benefits of good ol' sisterhood. Sisterboss even funds girls' educations in Kenya. Heck yeah, Lily. Xo.","img/lily-singh","https://en.wikipedia.org/wiki/Lilly_Singh",""]);
badass.push(["Angela James","Ice Breaker","Angela James has been named the National Women's Hockey League's Most Valuable Player six times, is openly gay, and of black heritage. Guess which one of those three facts is relevant to her career? After an offended father banned young Angela from playing hockey because she was better than his son, her mother put her in more senior teams, where she took on older girls and won. H8ters, you're benched.","img/angela-james","https://en.wikipedia.org/wiki/Angela_James",""]);
badass.push(["Jean Augustine","Do You Know Why You Were Sent Here Today, Canada?","Know why you don't want to be sent to the principal's office in school? Because they see right through your crap excuses, and set you straight. Well, former principal Jean Augustine thought Canada needed a little metaphorical kick to the behind, so she became a Liberal member of the House of Commons, the first African-Canadian woman MP. And duh, ladyboss set everybody straight.","img/default","https://en.wikipedia.org/wiki/Jean_Augustine","dark"]);
badass.push(["Anne Cools","Super-Cools Senate Sister","Is Anne Cools as groovy as her name suggests? No. She's even GROOVIER. Where do I even begin? For starters, she was the first black Canadian appointed to Canada's upper house. Nice. Also, she was the first female black senator in all of North America. Cooler. ALSO she's so dang good at senate-ing that she's still going strong as the longest serving member. Coolest. ","img/default","https://en.wikipedia.org/wiki/Anne_Cools","dark"]);
badass.push(["Frances Oldham Kelsey ","Thalidomide Slayer","If a powerful pharmaceutical company came to you for approval and said: \"All the cool countries are doing it&hellip;\" would you step up and go: \"Hold up, though\"? The FDA's Frances Oldham Kelsey sure as heck did. She told the makers of thalidomide where they could shove it, and she didn't mean orally. She protected kids, she kicked butt, she even shared the credit.","img/default","https://en.wikipedia.org/wiki/Frances_Oldham_Kelsey","dark"]);
badass.push(["Carol Huynh","The Woman with the Golden Hold","Throwing opponents to the mat? Boss. Winning Canada's first-ever Olympic gold medal in wrestling? Bosser. Oh, and Carol Huynh figured she'd pick up a bronze medal at the next one too. NBD. Her whimpering rivals don't have to look far for guidance: her master's degree in counselling psychology oughtta do the trick.","img/default","https://en.wikipedia.org/wiki/Carol_Huynh","dark"]);
badass.push(["Samantha Bee","Comedy's Queen Bee","Samantha, girl... thanks for cutting through the bull. On Full Frontal With Samantha Bee, bigots, chauvinists, wingnuts and liars all suffer the same fate under her hilariously unimpressed \"ORLY\" glare, and sharp wit. Full Frontal deals with feminist and political issues as they deserve: with clever, categorical mockery. Mess with the Bee, you gonna get stung.","img/default","https://en.wikipedia.org/wiki/Samantha_Bee","dark"]);
badass.push(["Adrienne Clarkson","Her Excellency, The Right Honourable Madam Slayer","When Hong Kong-born, Adrienne Louise Clarkson n&eacute;e Poy arrived as a refugee from Japanese-occupied China, she hoped for a better life. So, naturally, she earned a number of university degrees, became a producer and broadcaster for CBC, became a stateswoman to serve as Governor General of Canada, and was sworn into the Freakin' Queen's Privy Council. SO. Better life? Check.","img/adrienne-clarkson","https://en.wikipedia.org/wiki/Adrienne_Clarkson",""]);
badass.push(["Michaëlle Jean","Former GG, Cool AF","As non-idiots already know, refugees make our country better. Want proof? Watch Michaëlle Jean come over from Haiti, rise through the CBC until they went ahead and named a show after her, then get tapped to be the queen's #1 wing lady. And how's our former governor-general spending retirement? She's secretary-general of the Organization internationale de la Francophonie, AKA: l'ultime boss.","img/michaelle-jean","https://en.wikipedia.org/wiki/Micha%C3%ABlle_Jean",""]);
badass.push(["Samantha Nutt","Local Inspiration, Global Leader ","Canadian-born Samantha Nutt spent her childhood in South Africa becoming a fierce woman of the world. A physician who worked in war zones for 16 years, saint-like Samantha founded War Child Canada, and continues to tirelessly advocate for human rights issues. I'm gonna go ahead and throw out there that she might actually be the best person in the world. Anyone want to disagree? Anyone?","img/samantha-nutt","https://en.wikipedia.org/wiki/Samantha_Nutt","dark"]);
badass.push(["Sheila Watt-Cloutier","Just Saving the Earth Over Here, NBD","Sheila Watt-Cloutier doesn't wake up, send a few emails and say, meh, now I'mma take a nap. Nope. She aims big. Really big. Like the actual entire world big. This Inuit boss activist has been nominated for a Nobel Peace Prize for outlining the impact global climate change has on human rights. (Sounds important? That's cuz it is.) When the world DOESN'T melt, we'll be like: \"Thanks, Sheila.\"","img/default","https://en.wikipedia.org/wiki/Sheila_Watt-Cloutier","dark"]);
badass.push(["Alice Munro","The Fantastic and Ordinary Lives of Girls and Women","Where would we be without Alice Munro? SAD AND ALONE. Alice's masterful architecture and astounding imagination mean we get to read fiction that celebrates nuance (nice!) plays with time (neat!), explores the human condition (whoa!) and rewards empathy (emotions!) Basically: genius Alice makes you laugh, makes you cry, and makes you think. Which is important (look it up). ","img/alice-munro","https://en.wikipedia.org/wiki/Alice_Munro",""]);
badass.push(["Margaret Atwood","The Readable Woman","How do you take your literary feminism? Margaret Atwood serves it up: hot and fresh. You want some reflection on gender roles? BAM! The Edible Woman. Dystopian science fiction? KAPOW! The Handmaiden's Tale. Or, heck, a comic about a catman? BOOM! Angel Catbird. And if you're not hungry for reading, just watch her school a braying, populist jerk about the importance of public libraries. Mmm! Delicious.","img/default","https://en.wikipedia.org/wiki/Margaret_Atwood","dark"]);
badass.push(["Sarah Polley","National Treasure to the Max","Actor, director, writer, activist &mdash; Sarah Polley turns being a Canadian Icon up to eleven. (Seriously, ask anyone above the 49th.) Child stardom might have been enough for some other losers, but Sarah Polley asked herself one question: \"Is there anything I can't do?\" The answer? \"lol, nope.\"","img/default","https://en.wikipedia.org/wiki/Sarah_Polley","dark"]);
badass.push(["Hayley Wickenheiser","Wickenheiser FTW (All of Them)","Team Canada captain and overall Boss Lady Hayley Wickenheiser is glittery af. With GOLD MEDALS! That's how it goes when you're the best female hockey player in history, and are tied only with your teammates, Caroline Ouellette and Jayna Hefford for most gold medals of any Canadian Olympian. Wickenheiser's gender is awesome, duh, but also immaterial to her success as an athlete. Because, oh that's right: women are people too. ","img/hayley-wickenheiser","https://en.wikipedia.org/wiki/Hayley_Wickenheiser",""]);
badass.push(["Caroline Ouellette","She Shoots, She Does a Solid for Young People Everywhere","Caroline Ouellette is more than just a really, reeeeeeeally freakin' good hockey player. \"Caro\" to her friends co-founded athletichub.com, to help student athletes navigate the complicated-af recruitment process, and is an ambassador for Right to Play, an organization that teaches children in need through educational games. Girl also has more gold medals than most of us have fingers, assuming you're a bit clumsy.","img/default","https://en.wikipedia.org/wiki/Caroline_Ouellette","dark"]);
badass.push(["Nadine Caron","Winning at Being First","Nadine Caron isn't always first, but&hellip; no wait, no actually she is. First in her class, first choice doctor; heck, Nadine's the first Canadian female general surgeon of First Nations descent. Girlfriend's even got some first place athletic awards under her belt because yeah sure why not. Jealous of her glittering golds? You're not the first.","img/default","https://en.wikipedia.org/wiki/Nadine_Caron","dark"]);
badass.push(["Kirstine Stewart","140 Characters of Boss","Kirstine Stewart wrote the book on female leadership, literally. Our Turn, published in 2013, is a call to other ambitious lady bosses of the world. Hope she knows what she's talking about after being the former VP of media for Twitter North America, CBC's executive director of programming and now the chief strategy officer at Diply... Y'know what? I think she's got this business thing locked down.","img/default","https://en.wikipedia.org/wiki/Kirstine_Stewart","dark"]);
badass.push(["Attiya Khan","Asking: \"How Can We Help?\"","Instead of drop-kicking the face of her former abusive boyfriend into a river of extra-stingy lava, Toronto's Attiya Khan took the (alright, fine) super high road and asked him if he wanted \"to talk.\" Incredible, brave and innovative Attiya is making a film about it, in order to shed light on the \"intolerably high\" rate of violence against women in Canada, and everywhere. ","img/default","http://www.macleans.ca/news/canada/i-think-some-men-who-use-violence-can-change/","dark"]);
badass.push(["Lucy Decoutere","Speak Your Truth","Whether you know her as Lucy from Trailer Park Boys, captain Decoutere in the Royal Air Force or as Lucy, the first woman to publicly allege former Radio Host Jian Gomeshi of sexual assault, Lucy Decoutere is all kinds of #bold. Lucy braved public defamation to fight for what she believed in, and even after hearing an unsatisfactory verdict, she remains heroic, and funny as hell. #imwithher","img/lucy-decoutere","https://en.wikipedia.org/wiki/Lucy_DeCoutere","dark"]);
badass.push(["k.d.lang","A Constant Craving For Not Giving a F","k. d. lang is the powerful lady she is and if you aren't on board with that, you can legit GTFO. Incredibly tallented and hugely inspirational, k.d. braved coming out to the country music industry 1993, and, even more controversially, as a proselytising vegetarian in 1990. After being banned on dozens of radio stations do you think k.d. backed down? &hellip; Do you? ('Cause super no.)","img/kd-lang","https://en.wikipedia.org/wiki/K.d._lang","dark"]);
badass.push(["Joni Mitchell","\"A Painter Derailed by Circumstance\"","Roberta Joan Mitchell is one of the greatest song writers of all time. Period, thank you, we're done here, goodnight. Somehow wise on all things &mdash; from art, to motherhood, to the passing of time &mdash; Joni puts her finger on the human condition so beautifully and acutely, her soprano/contralto voice became that of a generation. Joni: self-taught musician, beautiful soul, woman made to inherit the earth.","img/joni-mitchell","https://en.wikipedia.org/wiki/Joni_Mitchell","dark"]);
badass.push(["Dianna Boileau","Trans Pioneer","Born with boy-parts in the 1930s, Dianna Boileau always knew she was a girl, eventually undergoing one of Canada's first gender-confirming surgeries in 1970. The nosy country was all, \"Wait, WHAT? Tell us everything!\" So, Dianna held a press conference and published a book, Behold, I Am Woman, even though it was defs none of their damn business. Then she happily left the spotlight and got to live her life. Finally.","img/default","https://www.thestar.com/news/insight/2016/03/27/the-woman-who-was-trans-before-her-time.html","dark"]);
badass.push(["Catherine Callbeck","Premier League","In 1993, PEI's Liberals were looking for a new leader, and Catherine Callbeck said, \"Meh, I'm not doing anything.\" Then she called an election, led the party to an historic victory and became the first elected female premier in Canada (*shrugs*). Although the recently retired senator has often been the only woman in the room, she still downplays her trailblazing ways: \"I just crushed politics and broke barriers. No biggie.\"","img/default","https://en.wikipedia.org/wiki/Catherine_Callbeck","dark"]);
badass.push(["Julie Payette","Out of this World","\"Please tell us about yourself, Ms. Payette.\" \"Well, I was the first Canadian to work on the International Space Station, was chief astronaut for the Canadian Space Agency, and now I'm a director of the National Bank of Canada and the Canadian Olympic Committee. I've also sung with the Montreal Symphony Orchestra.\" \"Okay&hellip; let's move on to your weaknesses.\" \"Um&hellip; hold on k I'll think of one&hellip;\" ","img/julie-payette","https://en.wikipedia.org/wiki/Julie_Payette",""]);
badass.push(["Ellen Page","\"I Am Tired of Hiding\"","Ellen Page is cooler than everyone else, everywhere, ever, in the following ways: She's a self-described pro-choice feminist, a yoga-practicing vegan, an atheist, an activist, and openly gay. Every one of her movies is basically your favourite movie, (Juno, Inception), and when she opens her mouth, this happens: \"This world would be a whole lot better if we just made an effort to be less horrible to one another.\" Um, yep.","img/ellen-page","https://en.wikipedia.org/wiki/Ellen_Page",""]);

function make() {
    // replaces elements in layout with a random person from the badass array
    document.getElementById("badassName").innerHTML = badass[randomNumber][0];
    document.getElementById("badassSub").innerHTML = badass[randomNumber][1];
    document.getElementById("badassBio").innerHTML = badass[randomNumber][2];
    document.getElementById("badassLink").setAttribute("href", badass[randomNumber][4]);
    if (window.matchMedia("(min-width: 750px)").matches) {
        console.log(badass[randomNumber][3]);
        if(badass[randomNumber][3] === "img/default"){
            document.getElementById("badassPerson").style.backgroundImage = "url(img/default-dark-big.jpg)";
        }else{
            document.getElementById("badassPerson").style.backgroundImage = "url(" + badass[randomNumber][3] + "-big.jpg)";
        }
    } else {
        if(badass[randomNumber][3] === "img/default"){
            document.getElementById("badassPerson").style.backgroundImage = "url(img/default-dark-sml.jpg)";
        }else{
            document.getElementById("badassPerson").style.backgroundImage = "url(" + badass[randomNumber][3] + "-sml.jpg)";
        }
    }

    if (badass[randomNumber][5]==="dark") {
        document.getElementById("badassPerson").classList.remove('light');
        document.getElementById("badassPerson").classList.add('dark');
        document.body.style.backgroundColor = "black";
    } else {
        document.getElementById("badassPerson").classList.add('light');
        document.getElementById("badassPerson").classList.remove('dark');
        document.body.style.backgroundColor = "white";
    }
}

function next() {
    randomNumber++;
    make();
}

function rando() {
    randomNumber = Math.floor(Math.random() * badass.length);
    make();
}


//==============================================================
//PRIMARY FUNCTION (EXECUTES WHEN PAGE IS LOADED)
//==============================================================

document.addEventListener('DOMContentLoaded', function (event) {

    if(randomNumber > badass.length){
        rando();
    }else{
        make();
    }
    document.getElementById("random").addEventListener("click", rando);

    //DEBUG
    // next();
    // document.getElementById("bold_logo").addEventListener('click', next);

});
